jg/121/create-CreditAmortization-page
selsa-inube/personas pull request #105
Opened 2023-08-25 12:33 UTC by novadeveloper14

2023-08-25 15:25 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-08-25 16:56 UTC, Sebas3245 requested changes
A los valores en los registros de la tabla de plan de pagos les falta el formato correcto y el signo de pesos.

Además, creo que va a tocar ajustar la tabla porque la paginación en el figma aparece dentro del recuadro de la tabla y no por fuera.

2023-08-25 16:56 UTC, Sebas3245 commented on src/pages/admin/credits/CreditAmortization/index.tsx
> +    ISelectedProductState | undefined
No hace falta ni definir el tipo undefined ni declararlo ya que con solo dejar () vacio ya que entendera como "| undefined"

2023-08-28 13:06 UTC, Sebas3245 requested changes
Se estan añadiendo unos decimales ",00" en los valores, eliminemoslos:
![image](https://github.com/selsa-inube/personas/assets/55991750/8cb69bf0-59db-4a73-95b3-1a2242ad7983)

2023-08-28 13:06 UTC, Sebas3245 commented on src/pages/admin/credits/CreditAmortization/index.tsx
> +  function formatCurrency(value: number) {
Ya existe esta función en:

src\pages\admin\credits\MyCredits\AmountValue\index.tsx

como ya requerimos usarla en dos lugares propongo generalizarla en un archivo src/utils/formats.ts

Adicionalmente quiero hacer una recomendación para futuros desarrollos, cuando se crean este tipo de funciones dentro del componente, si la función no necesita de algún estado o referencia ya sea obtener su valor o setearlo, o directamente hacer uso de algún hook si no que se trata de una función que simplemente recibe un valor y retorna otro, podemos asegurar el rendimiento del componente dejando la función por fuera del mismo, recomiendo leer este articulo relacionado: 

[writing-functions-outside-vs-inside-in-react](https://medium.com/the-fours/writing-functions-outside-vs-inside-in-react-c9044ea31ee2)

2023-08-28 14:09 UTC, Sebas3245 approved these changes

2023-08-28 14:09 UTC, merged