jg/147/mock-investment-products
selsa-inube/personas pull request #106
Opened 2023-08-25 16:21 UTC by novadeveloper14

2023-08-25 19:23 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-08-25 19:47 UTC, Sebas3245 requested changes

2023-08-25 19:47 UTC, Sebas3245 commented on src/types/pages/product.types.ts
> +  label?: string;
Los atributos deben ser solo:

id: string;
  label: string;
  value: number | string;
 
 para extraerlos como se hace en src\pages\admin\home\config\products.tsx
 
 
![image](https://github.com/selsa-inube/personas/assets/55991750/f4a6dd2d-5dc1-4032-811d-b43f14b0b5ee)

 
 Para integrarlos correctamente a los mocks sebe hacerlo como en:
 src\mocks\products\credits\credits.mocks.tsx 
 
![image](https://github.com/selsa-inube/personas/assets/55991750/1dc9b653-0b82-44cf-9f0a-7db3229a98ef)

2023-08-28 12:52 UTC, Sebas3245 approved these changes

2023-08-28 12:52 UTC, merged