jg/138/Use-currencyFormat-on-my-credits-pages
selsa-inube/personas pull request #115
Opened 2023-08-29 15:26 UTC by novadeveloper14

2023-08-29 18:47 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-08-29 21:29 UTC, Sebas3245 requested changes

2023-08-29 21:29 UTC, Sebas3245 commented on src/pages/admin/credits/MyCredits/config/products.tsx
> +    if (typeof attribute.value === "number") {
Nada nos asegura que todos los atributos de tipo number sean valores de dinero, la funcion de extract solo debe retornar los valores de cada atributo y ya como se representen depende de donde se estan extrayendo, para lograr esto podriamos hacer una funcion de mapeo en los config de cada lugar donde se requiere y asi dependiendo del contexto se sabra a cuales valores aplicarle el currencyFormat puntualmente.

2023-08-29 21:29 UTC, Sebas3245 commented on src/pages/admin/home/config/products.tsx
>  function extractCreditAttributes(credit: IProduct) {
Mismo caso que el comentario anterior.

2023-08-29 21:29 UTC, Sebas3245 commented on src/pages/admin/home/config/products.tsx
>  function extractInvestmentAttributes(investment: IProduct) {
Igual que el comentario sobre la función extracción.

2023-08-30 22:30 UTC, Sebas3245 approved these changes
Excelente

2023-08-30 22:30 UTC, merged