jg/166/Change-values-on-credits-mocks
selsa-inube/personas pull request #116
Opened 2023-08-29 16:00 UTC by novadeveloper14

2023-08-29 22:49 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-08-30 00:26 UTC, Sebas3245 requested changes
Los valores aún son muy similares en los dos mocks que tenemos de crédito, cambie las descripciones de los movimientos y los valores de dinero de amortización que empiecen con otro numero

2023-08-30 12:43 UTC, Sebas3245 requested changes
En los movimientos cambiemos el primer numero que tiene el valor total de los registros de movimientos y tambien el primero numero que tiene la cuota de los registros de amortizacion de **uno de los productos mockeados**.

2023-08-30 13:15 UTC, Sebas3245 approved these changes

2023-08-30 13:16 UTC, merged

2023-08-30 13:16 UTC, Sebas3245 commented
solved #100