jg/188/mock-SavingsAccount-details-page
selsa-inube/personas pull request #144
Opened 2023-09-05 16:57 UTC by novadeveloper14

2023-09-05 23:44 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-09-06 13:38 UTC, Sebas3245 requested changes

2023-09-06 13:38 UTC, Sebas3245 commented on src/pages/admin/savings/SavingsAccount/config/navigation.ts
> +    isActive: false,
No le pasemos el isActive: false, como es propiedad opcional, con solo no pasarle el isActive ya funciona bieen

2023-09-06 13:38 UTC, Sebas3245 commented on src/mocks/products/savings/savings.mocks.tsx
> +    savingMovements: [
Utilicemos movements como propiedad es decir no añadir una nueva propiedad al IProduct, la idea es que sea lo mas general posible, entiendo que usando "movements" le sale obligatorias algunas propiedades, podemos dejarlas como opcionales y ajustar donde sea necesario

2023-09-06 13:38 UTC, Sebas3245 commented on src/pages/admin/savings/SavingsAccount/config/saving.tsx
> +const savingBox = {
Llamemoslo savingsAccountBox, recordemos que habre diferentes savings y tendremos que ser especificos para no tener luego confusiones en mportaciones

2023-09-06 14:42 UTC, Sebas3245 approved these changes

2023-09-06 14:42 UTC, merged