feat(nav): migrate nav component to typeScript
selsa-inube/personas pull request #15
Opened 2023-07-26 21:07 UTC by ANGIECATHERINEP

2023-07-26 22:22 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-07-26 23:04 UTC, Sebas3245 requested changes

2023-07-26 23:04 UTC, Sebas3245 commented on src/design/layout/Page/types.ts
> +interface Isections{
Deberia ser "ISections"

2023-07-27 12:36 UTC, Sebas3245 approved these changes

2023-07-27 12:36 UTC, merged