Cr/222/mock page for savings commitments
selsa-inube/personas pull request #179
Opened 2023-09-14 13:48 UTC by CristianRojas-47

2023-09-14 17:05 UTC, novadeveloper14 requested changes
al realizar los siguientes comandos en la terminal: 
1. npm i -g typescript
2.  tsc
podemos ver que se esta presentando un error de tipado en la siguiente ubicación:
src/mocks/products/investments/investmentsCommitments.mocks.tsx

2023-09-14 17:05 UTC, novadeveloper14 commented on src/mocks/products/savings/savingsCommitments.mocks.tsx
si el compromiso es obligaciones estatutarias entonces en el box debe de mostrar que esta en mora y tambien debe de mostrar los productos:

1. 201 - 91214069
2. 200 - 91214069

![image](https://github.com/selsa-inube/personas/assets/87447257/1c2d9990-a102-4077-aae8-9b1156731317)

2023-09-15 04:05 UTC, novadeveloper14 requested changes
falta hacer que en Obligaciones estatutarias en el Box aparezca el componente tag en mora también:

![image](https://github.com/selsa-inube/personas/assets/87447257/8e848f15-c7b7-4dfb-836b-50c536d309ee)

https://www.figma.com/file/tVCel8FnrVZYoFCISHClKG/Mockups?node-id=2045%3A41412&mode=dev

2023-09-15 23:34 UTC, novadeveloper14 approved these changes
El desarrollo es correcto.

2023-09-18 17:09 UTC, Sebas3245 requested changes

2023-09-18 17:09 UTC, Sebas3245 commented on src/pages/admin/savings/SavingsCommitments/interface.tsx
> +                selectedCommitment.commitment.products.map((commitment) => {
Podemos crear una funcion "renderProducts" que reciba selectedCommitment.commitment.products como parametro y dentro de esta añadir toda esta logica de JS para crear constantes y condicionales dentro del JSX

2023-09-18 17:12 UTC, Sebas3245 reviewed
La separacion del select, el box de atributos y el box de productos en MOBILE, no es la misma que aparece en los mockups:


App:
![image](https://github.com/selsa-inube/personas/assets/55991750/b9093565-7589-4717-91b2-096bd3599a84)


Figma:
![image](https://github.com/selsa-inube/personas/assets/55991750/4c802f6d-3db3-4d11-bf60-be7bafd69b9c)

2023-09-19 14:10 UTC, Sebas3245 requested changes

2023-09-20 13:34 UTC, merged