jg/36/migrate-NavLink-to-TypeScript
selsa-inube/personas pull request #18
Opened 2023-07-26 21:43 UTC by novadeveloper14

2023-07-26 22:39 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2023-07-26 23:08 UTC, Sebas3245 requested changes

2023-07-26 23:08 UTC, Sebas3245 commented on src/design/navigation/NavLink/index.tsx
> +  path: string;
Segun los proptypes anteriores, path deberia ser opcional, verificar si se puede asignar sin tener que cambiar otra parte del codigo

2023-07-26 23:08 UTC, Sebas3245 commented on src/design/navigation/NavLink/styles.ts
> +interface IStyledLink extends IStyledNavLink {}
**Evitemos a toda costa el extends con declaración vacia "{}"**, en este caso pues crear IStyledLink igual a IStyledNavLink con la propiedad selected pero que sean interfaces aparte, el extends solo aplicaría si debemos crear una interfaz que tiene las mismas propiedades que otra, pero necesitamos añadirle más que sean propias de la nueva interfaz

2023-07-27 12:37 UTC, Sebas3245 approved these changes

2023-07-27 12:38 UTC, merged