jg/279/Mock-service-relates-select-whit-domain-values
selsa-inube/personas pull request #203
Opened 2023-09-21 17:49 UTC by novadeveloper14

2023-09-21 19:06 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-09-21 21:45 UTC, Sebas3245 requested changes

2023-09-21 21:45 UTC, Sebas3245 commented on src/mocks/domains/domainService.mocks.ts
> +  city: cityDM.options,
La idea es mockear aca los listados como llegarian desde un back-end, no usar los que ya tenemos dentro de model/domains.

2023-09-21 21:48 UTC, Sebas3245 commented on src/mocks/domains/domainService.mocks.ts
> +  city: cityDM.options,
Preferiblemente yo creo que mejor dejarlos en archivos aparte dentro de mocks/domains, no importa que estemos duplicando los dominios, la idea es simular completamente esa informacion como si llegara del back-end.

2023-09-21 23:11 UTC, Sebas3245 requested changes

2023-09-21 23:11 UTC, Sebas3245 commented on src/mocks/domains/domainService.mocks.ts
> +function getDomainById(domainId: string): ISelectOption[] {
No deje implicito que lo retorna es de tipo ISelectOption, que sea de cualquier estructura que sea el mock, es decir no le coloque un tipo al return, tanto para esta funcion como para la otra

2023-09-21 23:11 UTC, Sebas3245 commented on src/mocks/domains/domainService.mocks.ts
> +  return domainIds.map((id) => getDomainById(id));
Aca el problema es que retorna un listado muy largo y sin saber cuál es la separacion de cada uno, haga que la funcion retorne un objeto que segun cada dominio envuelva en una propiedad (con el nombre del dominio) cada uno con su respectivo listado de valores

2023-09-22 11:48 UTC, Sebas3245 approved these changes

2023-09-22 11:48 UTC, merged