Cr/299/adjust readonly input
selsa-inube/personas pull request #218
Opened 2023-09-25 12:58 UTC by CristianRojas-47

2023-09-25 22:04 UTC, novadeveloper14 approved these changes

2023-09-26 13:03 UTC, Sebas3245 requested changes
Entiendo el objetivo del issue, sin embargo, me da curiosidad que en el Figma aun salgan grisáceos los inputs que son de solo lectura, hablar con leonardo con respecto a si como están en este desarrollo es el color correcto de como deberían aparecer, y si es así para también actualizar el Figma.

2023-09-26 18:21 UTC, Sebas3245 approved these changes

2023-09-26 18:21 UTC, merged

2023-09-26 18:22 UTC, Sebas3245 commented
solved #209