Cr/252/create fullscreen nav component
selsa-inube/personas pull request #219
Opened 2023-09-26 02:31 UTC by CristianRojas-47

2023-09-27 14:17 UTC, novadeveloper14 requested changes

2023-09-27 14:17 UTC, novadeveloper14 commented on src/design/fullscreenNav/FullscreenNav.stories.tsx
> +export const Default = (args: FullScreenNavProps) => (
dejemos en la storie por defecto tal cual lo muestra en los designs cuando recibe dos subtitulos o menos (no colapsable), y creemos otra para cuando sea colapsable osea mas de dos subtitulos

2023-09-27 14:17 UTC, novadeveloper14 commented on src/design/fullscreenNav/props.ts
acá creemos un parameters el cual es una descripción general de el componente y después pasémoselo a la story 

ejemplo:
![image](https://github.com/selsa-inube/personas/assets/87447257/f81d4002-7f7e-4b88-b4d1-2e589104e057)
![image](https://github.com/selsa-inube/personas/assets/87447257/9c846eae-f47f-437d-b53d-f996ac8f8386)

2023-09-29 21:28 UTC, novadeveloper14 approved these changes
El desarrollo es correcto.

2023-09-29 22:04 UTC, Sebas3245 requested changes

2023-09-29 22:04 UTC, Sebas3245 commented on src/design/navigation/fullscreenNav/MultiSections/index.tsx
> +    const updatedState: { [sectionName: string]: boolean } = {};
Esta funcion se puede simplificar y optimizar de la siguiente manera:

```typescript
const handleCollapse = (sectionName: string) => {
    setSectionCollapse((prev) =>
      Object.fromEntries(
        Object.entries(prev).map(([key]) => [key, key === sectionName])
      )
    );
  };
```

2023-09-29 22:04 UTC, Sebas3245 commented on src/design/navigation/fullscreenNav/MultiSections/index.tsx
> +  }>(() => {
Toda esta logica la podemos simplificar a: 

```typescript
}>(() => ({
    [combinedSectionValues[0].title]: true,
    ...combinedSectionValues.slice(1).reduce(
      (section, sectionValue) => ({
        ...section,
        [sectionValue.title]: false,
      }),
      {}
    ),
  }));
```

2023-09-29 22:04 UTC, Sebas3245 commented on src/design/navigation/fullscreenNav/MultiSections/index.tsx
> +  const navigationSectionValues = Object.values(navigation.sections);
Podemos simplificar esto y la creacion de la constante combinedSectionValues de la siguiente manera:

```typescript
const combinedSectionValues = [
    ...Object.values(navigation.sections),
    ...(links || []).map((link) => ({ title: link.label, links: [link] })),
  ];

```

2023-09-29 22:37 UTC, Sebas3245 commented on src/design/navigation/fullscreenNav/MultiSections/index.tsx
> +  const navigationSectionValues = Object.values(navigation.sections);
Creo que falta este ajuste, o esa simplificacion le esta dando errores?

2023-09-29 23:04 UTC, Sebas3245 approved these changes

2023-09-29 23:04 UTC, merged