jg/311/Change-placeholder-and-validationMessages-for-dates-fields
selsa-inube/personas pull request #229
Opened 2023-09-27 22:51 UTC by novadeveloper14

…ssage format

2023-09-27 23:02 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-09-27 23:22 UTC, Sebas3245 requested changes

2023-09-27 23:22 UTC, Sebas3245 commented on src/validations/validationMessages.ts
> +    "Formato de fecha incorrecto. Use el formato: dd/mes/aaaa (por ejemplo, 01/Ene/1990).",
Acortemos este texto yo creo que podemos omitir el "Use el formato: dd/mes/aaaa" y dejar "Ejemplo de formato: 01/Ene/1990 "

2023-09-28 12:44 UTC, Sebas3245 approved these changes

2023-09-28 12:44 UTC, merged

2023-09-28 12:44 UTC, Sebas3245 commented
solved #227