jg/287/Mock-and-render-ContactDataForm
selsa-inube/personas pull request #236
Opened 2023-09-29 07:23 UTC by novadeveloper14

2023-09-29 17:21 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-09-29 18:15 UTC, Sebas3245 requested changes

2023-09-29 18:15 UTC, Sebas3245 commented on src/mocks/users/users.mocks.tsx
> +        city: "Bogota",
Aca va el codigo del dominio, por eso estaba en minuscula sin la tilde, corregir, si quiere obtener el valor puede utilizar una funcion valueOf como se hizo en este desarrollo: https://github.com/selsa-inube/personas/pull/237

2023-09-29 18:15 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
> +      <Fieldset title="Dirección N° 01">
Como se aclaro en el diseño, aca deberia traer ese consetivo "01" segun el index de contactData en el mock ya que ese deberia ser ahora un arreglo

2023-10-02 15:44 UTC, Sebas3245 requested changes
El tamaño de los inputs es muy grande en relación al figma y a los otros formularios del asistido

2023-10-02 17:26 UTC, Sebas3245 requested changes

2023-10-02 17:26 UTC, Sebas3245 commented on src/mocks/domains/cityType.ts
> +const cityData = [
No creemos esta simulación de dominio, usemos el de model/domains/personalInformation

(Esto porque son valores que no necesitamos explícitamente del "back-end", si no que podemos tenerlos en la aplicacion para acortar futuros tiempos de respuesta)

2023-10-02 17:26 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
> +    ...formik,
Aca podemos retornar directo el formik sin clonar un objeto spred:

```typescript
useImperativeHandle(ref, () => formik);
```

2023-10-03 02:27 UTC, Sebas3245 requested changes

2023-10-03 02:27 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
> +            value={cityDMValueOf(formik.values.city)?.value}
La idea no es exportar cityDMValueOf y usarlo por separado del dominio, cityDM tiene una propiedad valueOf con la cual podemos acceder a esa funcion, con eso se logro enlazar metodos a la instancia/clase cityDM

2023-10-03 03:18 UTC, Sebas3245 approved these changes

2023-10-03 03:18 UTC, merged