jg/290/Mock-and-render-BankTransfersForm
selsa-inube/personas pull request #238
Opened 2023-10-01 13:47 UTC by novadeveloper14

2023-10-02 16:40 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-02 17:34 UTC, Sebas3245 requested changes

2023-10-02 17:34 UTC, Sebas3245 commented on src/pages/general/UpdateData/types.ts
> +  bankTransfers: IBankTransfersEntry;
Ubiquemos esta nueva propiedad en el mismo orden en el que estan los pasos segun el assisted.ts, aca y donde se requiera hacer lo mismo en UpdateData para conservar ese orden en el codigo

2023-10-03 03:19 UTC, Sebas3245 requested changes
Resolver conflictos

2023-10-04 13:25 UTC, Sebas3245 approved these changes

2023-10-04 13:25 UTC, merged