jg/314/Mock-and-render-PersonalResidenceForm-update-data
selsa-inube/personas pull request #245
Opened 2023-10-04 06:25 UTC by novadeveloper14

2023-10-04 20:46 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-04 22:44 UTC, Sebas3245 requested changes

2023-10-04 22:44 UTC, Sebas3245 commented on src/design/input/Select/styles.ts
> +  outline: 1px solid
Hay que usar la propiedad border, ya que esta si le agrega tamaño al elemento mientras que outline no, y si revisamos el Figma nos damos cuenta que el componente esta representado de tal forma que el borde si agrega espacio al elemento: 
![image](https://github.com/selsa-inube/personas/assets/55991750/66642299-c20e-4b59-a93b-99385e49714c)

2023-10-04 22:44 UTC, Sebas3245 commented on src/model/entity/user.ts
> +  personalResidence: IPersonalResidence;
cambiemos el nombre de esta propiedad y de la interfaz a solo "Residence" y que sea una propiedad que haga parte de "IPersonalData"

2023-10-04 22:44 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalResidenceForm/interface.tsx
> +        {formik.values.type === "ownWithMortgage" && (
en estas validaciones debemos usar el objeto del dominio es decir residenceTypeDM.OWN_WITHOUT_MORTGAGE.id en este caso, el objetivo de esto seria que no quememos valores en cadenas para hacer comparaciones y que si el dia de mañana hay que cambiar el dominio no tengamos que estar cambiando todos los archivos si no que solo con cambiar los valores en el archivo del dominio ya se haria de manera general.

2023-10-04 22:44 UTC, Sebas3245 commented on src/validations/validationRules.ts
> +  bankingEntity: Yup.string()
Yo creo que en lugar de crear esta regla podemos usar la "name" y aparte aprovechando eliminemos la de "lastName" ya que creo que no se esta usando, y si se esta usando reemplazarla con "name" donde sea el caso.

2023-10-05 13:05 UTC, Sebas3245 approved these changes

2023-10-05 13:05 UTC, merged