Cr/316/mock and render informacion socioeconomica form
selsa-inube/personas pull request #246
Opened 2023-10-04 12:20 UTC by CristianRojas-47

2023-10-04 14:18 UTC, novadeveloper14 requested changes
Solucionar conflictos

2023-10-04 16:05 UTC, novadeveloper14 requested changes

2023-10-04 16:05 UTC, novadeveloper14 commented on src/model/domains/personalInformation/educationLeveldm.ts
tanto educationLevelTypeDM como vulnerablePopulationTypeDM podemos crear otra carpeta aca en model/domains que se llame  socioeconomicInformation y almacenar los archivos mejor ahí.

2023-10-04 20:34 UTC, novadeveloper14 requested changes
en varias partes de el desarrollo tanto en declaraciones como en nombres de carpetas puso el nombre SocioEconomic pero Socioeconomic es una palabra completa por lo que la "e" seria en minúscula, esto para respetar el pascal case o el camel case dependiendo el caso.

2023-10-04 20:34 UTC, novadeveloper14 commented on src/pages/general/UpdateData/config/assisted.ts
> +  personalSocioEconomicInformation: {
podemos eliminar el personal y dejar solo socioeconomicInformation: { ... }

2023-10-04 20:34 UTC, novadeveloper14 commented on src/pages/general/UpdateData/forms/PersonalSocioEconomicInformation/index.tsx
la carpeta todavía se llama PersonalSocioEconomicInformation

2023-10-04 22:53 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2023-10-05 13:19 UTC, Sebas3245 requested changes
Solucionar conflictos y ajustar según comentarios, importante que al solucionar los conflictos este form igual siga siendo el ultimo tanto en los pasos del asistido como en el orden de como está declarado dentro del código

2023-10-05 15:57 UTC, Sebas3245 approved these changes

2023-10-05 15:57 UTC, merged