Cr/306/extend textfield to support autocomplete
selsa-inube/personas pull request #253
Opened 2023-10-05 13:10 UTC by CristianRojas-47

2023-10-05 20:35 UTC, novadeveloper14 requested changes

2023-10-05 20:35 UTC, novadeveloper14 commented on src/design/input/TextField/TextField.stories.tsx
estaría bien una story con el autocompletado para comprobar el funcionamiento.

2023-10-09 22:59 UTC, novadeveloper14 approved these changes

2023-10-10 13:33 UTC, Sebas3245 requested changes

2023-10-10 13:33 UTC, Sebas3245 commented on src/design/input/TextField/interface.tsx
> +      (typeof autocompleteChars === "number"
autocompleteChars es un number por definicion, no hay necesidad de valdiar que este sea de este tipo, lo unico seria validar su existencia es decir que no sea undefined solo como "autocompleteChars  &&" o "autocompleteChars ? "

2023-10-10 13:33 UTC, Sebas3245 commented on src/design/input/TextField/interface.tsx
> +    const newValue = event.target.value;
Dejemos esta constante solo como "value"

2023-10-10 14:02 UTC, Sebas3245 approved these changes

2023-10-10 14:03 UTC, merged