jg/322/Mock-and-render-the-comentarios-step
selsa-inube/personas pull request #257
Opened 2023-10-07 07:30 UTC by novadeveloper14

2023-10-09 16:02 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-09 21:05 UTC, Sebas3245 requested changes

2023-10-09 21:05 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/interface.tsx
> +      ></Textarea>
Creo que aca se le fue la segunda etiqueta de cerrado para el TextArea

2023-10-09 21:05 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/CommentsForm/interface.tsx
> +        maxLength={250}
Deberia ser de 150

2023-10-10 13:37 UTC, Sebas3245 requested changes

2023-10-10 13:37 UTC, Sebas3245 commented on src/design/input/Textarea/index.tsx
> +    if (typeof onFocus === "function") {
onFocus si o si es una funcion por como esta declarada en la interfaz, esto son validaciones de JS que no son necesarias al usar TS, solo debe valdiar la funcion si llegue para invocarla, puede usar "onFocus && onFocus(e)" y lo mismo para el onBlur

2023-10-10 13:44 UTC, Sebas3245 approved these changes

2023-10-10 13:44 UTC, merged