jg/324/Mock-and-render-terminos-and-condiciones-step
selsa-inube/personas pull request #271
Opened 2023-10-11 15:46 UTC by novadeveloper14

2023-10-11 18:04 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-11 22:41 UTC, Sebas3245 requested changes
Falta actualizar el creditSimulationStepsRules con el nuevo paso para que se guarden los valores del mismo

2023-10-11 22:41 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/types.ts
> +  termsAndConditions: boolean;
cambiemos el nombre de esta propiedad a "accept"

2023-10-11 22:41 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/termsAndConditionsInfo.ts
> +const termsAndConditionsTexts = [
Estos textos dejemoslos en un directorio "config" dentro de "TermsAndConditionsForm" en un archivo llamado termsAndConditions.ts

2023-10-11 22:41 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/index.tsx
> +    if (handleSubmit) return;
Este handleSubmit no aplicaria si se va a hacer con el handleChange

2023-10-11 22:41 UTC, Sebas3245 commented on src/pages/request/credits/CreditSimulationRequest/forms/TermsAndConditionsForm/interface.tsx
> +interface TermsAndConditionsFormUIProps {
Dejemos la interfaz del componente siempre arriba de la declaración del mismo

2023-10-12 14:28 UTC, Sebas3245 approved these changes

2023-10-12 14:32 UTC, merged