jg/345/Adjust-step-of-financial-operations
selsa-inube/personas pull request #281
Opened 2023-10-12 17:05 UTC by novadeveloper14

2023-10-13 12:53 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-13 13:08 UTC, Sebas3245 requested changes
Ya que está modificando el TextArea y esta contextualizado, resolver el issue #283 en este desarrollo

2023-10-13 13:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
> +  const showFields =
Cambie el nombre de esta constante showFields a uno que sea mas descriptivo en contexto a los campos que se van a mostrar, que tampoco sea tan largo

2023-10-13 13:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FinancialOperationsForm/index.tsx
> +  descriptionOperationsForeignCurrency: Yup.string().required(
Coloquemosle una longitud minima de 1 y maxima de 300 a este campo aca en el esquema de validacion

2023-10-13 17:34 UTC, Sebas3245 requested changes

2023-10-13 17:34 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FinancialOperationsForm/interface.tsx
> +  const shouldShowForeignCurrencyFields =
quitemosle el "should"

2023-10-13 17:34 UTC, Sebas3245 commented
solved #283

2023-10-13 18:03 UTC, Sebas3245 approved these changes

2023-10-13 18:03 UTC, merged

2023-10-17 12:53 UTC, Sebas3245 commented
solved #262