jg/358/Turn-on-collapse-in-boxes-home
selsa-inube/personas pull request #294
Opened 2023-10-19 12:36 UTC by novadeveloper14

2023-10-19 13:29 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-19 23:30 UTC, Sebas3245 requested changes
Si bien está bien que ya permite hacer el collapse, en el figma no se ve que inicien colapsados cuando uno entra a la página, veo que el start está en false y aun así se inician colapsados, hay que revisar porque sucede y corregirlo.

2023-10-20 13:16 UTC, Sebas3245 requested changes
Hay que corregir el hecho de que, si start es true deberían están colapsados y si esta false no debería, en este momento está funcionando al revés

2023-10-20 16:46 UTC, Sebas3245 requested changes

2023-10-20 16:46 UTC, Sebas3245 commented on src/components/cards/Box/index.tsx
> +  const [collapse, setCollapse] = useState(!collapsing.start);
Si bien el operador de negación lo soluciona, al nivel de coherencia dentro de este componente si collapse es true pues lo colapsa, pero no tendría sentido decirle como "colapsado solo si es false", hay que quitar este operador de negación y buscar otra solución que mantenga la coherencia dentro del código y claramente sin cambiar el nombre del estado ya que está bien.

Tip: Donde se está usando esa constante "collapse" del estado dentro del componente y porque está funcionando al revés (obviamente sin el operador de negación que debemos quitar)?

2023-10-20 22:10 UTC, Sebas3245 approved these changes

2023-10-20 22:10 UTC, merged