Cr/323/mock and render desembolso step
selsa-inube/personas pull request #303
Opened 2023-10-20 00:21 UTC by CristianRojas-47

2023-10-20 16:22 UTC, novadeveloper14 requested changes

2023-10-20 16:22 UTC, novadeveloper14 commented on src/pages/request/credits/CreditSimulationRequest/forms/DisbursementForm/interface.tsx
en las validaciones de los campos en vez de usar el string literal puede usar el id de el dominio no dejemos los string quemados ya que estos son datos que vendrán de un backend.

ejemplos:

![image](https://github.com/selsa-inube/personas/assets/87447257/1904bc30-5f3e-4f8c-a940-d192e28f8a86)

![image](https://github.com/selsa-inube/personas/assets/87447257/b6339956-26b6-4b2e-9b78-a7ef2f1297ff)

2023-10-20 22:18 UTC, novadeveloper14 requested changes
verificar el siguiente error en consola cuando se interactúa con algunos de los campos:

![image](https://github.com/selsa-inube/personas/assets/87447257/53d7a70e-8989-416a-8c7a-50bd6aa8f4d4)

2023-10-21 01:30 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2023-10-23 01:43 UTC, Sebas3245 approved these changes

2023-10-23 01:43 UTC, merged