jg/382/Resolve-warning-from-formik.handleBlur-in-Select
selsa-inube/personas pull request #313
Opened 2023-10-23 12:18 UTC by novadeveloper14

2023-10-23 19:03 UTC, CristianRojas-47 requested changes
El error se sigue presentando y cuando se seleccionan una opción del producto que se desea el botón de siguiente no se habilita.
![Captura de pantalla 2023-10-23 135702](https://github.com/selsa-inube/personas/assets/93727887/114bf5d2-2b43-4508-82a6-446d000c3586)

2023-10-24 13:19 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-24 13:24 UTC, Sebas3245 approved these changes
Excelente solución

2023-10-24 13:25 UTC, merged

2023-10-24 13:25 UTC, Sebas3245 commented
solved #282