Cr/366/adjust delete button of personal references form
selsa-inube/personas pull request #324
Opened 2023-10-24 17:11 UTC by CristianRojas-47

2023-10-24 17:29 UTC, novadeveloper14 approved these changes

2023-10-25 15:52 UTC, Sebas3245 requested changes

2023-10-25 15:52 UTC, Sebas3245 commented on src/components/modals/DecisionModal/index.tsx
> +  const handleIsLoading = () => {
Si esta funcion solo se usa en handleConfirmationClick mejor no crearla y solo pasarle alla el setIsLoading(loading)

2023-10-25 15:52 UTC, Sebas3245 commented on src/components/modals/DecisionModal/index.tsx
> +  const handleConfirmationClick = () => {
Cambiemos el nombre de esta funcion a handleActionClick

2023-10-25 15:52 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalReferencesForm/DeleteReference/index.tsx
> +  const handleShowModal = () => {
Esta funcion y la de close modal podriamos cambiarlas por una handleToggleModal que tenga setShowModal(!showModal)

2023-10-25 15:52 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalReferencesForm/index.tsx
> +    const referenceIndex = formik.values.entries.findIndex(
La logica de esta funcion si lo que queremos es entonces eliminar un registro/indice de un arreglo podemos abreviarlo de la siguiente manera:

const updatedReferences = formik.values.entries.filter(
  (reference) => reference.id !== referenceId
);

formik.setFieldValue("entries", updatedReferences);


Con esto vamos a crear un nuevo arreglo que traiga todos los registros que no coincidan con el referenceId

2023-10-25 19:12 UTC, Sebas3245 approved these changes

2023-10-25 19:12 UTC, merged