jg/390/Redesign-SavingsCommitmentCard-according-to-new-mockups
selsa-inube/personas pull request #329
Opened 2023-10-26 15:36 UTC by novadeveloper14

2023-10-27 14:04 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-27 14:50 UTC, Sebas3245 requested changes
Ajustar la Card de tal manera que no reciba puntualmente que los únicos valores sean un valor de pago y una fecha si no que reciba los atributos y los mapee cómo funciona por ejemplo en AttributesModal, con eso nos aseguramos de que si más adelante se agrega otro atributo sea más fácil integrarlo, claramente eso quiere decir que a la hora de llamar este componente se deben obtener solo las propiedades que se van a mostrar en esa card.

2023-10-27 14:50 UTC, Sebas3245 commented on src/components/cards/SavingsCommitmentCard/SavingsCommintmentCard.stories.tsx
>    title: "Product name",
El nombre de este archivo esta mal

2023-10-27 14:50 UTC, Sebas3245 commented on src/components/cards/SavingsCommitmentCard/index.tsx
> +          <Icon size="16px" icon={<MdCalendarMonth />} spacing="none"></Icon>
Se le fue la etiqueta de cierre

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
Este archivo ya creció lo suficiente para que separemos en un interface.tsx.

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/index.tsx
>  import { Stack } from "@design/layout/Stack";
Este archivo ya crecio lo suficiente para que creemos un interface.tsx

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/index.tsx
> +function renderContent(mquery: boolean) {
Que esta función mejor se llame "renderMySavingsContent"

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/index.tsx
> +            <StyledCommitmentsContainer>
Este Container se va a renderizar aun si no hay compromisos

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
> +            <StyledCommitmentsContainer>
Este Container se va a renderizar aun si no hay compromisos

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
> +function renderContent(mquery: boolean) {
cambiemos el nombre de esta función a "renderHomeContent"

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
> +      {mquery && <QuickAccess links={quickLinks} />}
Se supone que "renderContent" se hace para no repetir el codigo al cambiar entre un tipo de dispositivo a otro, teniendo eso en cuenta esta validación de mostrar el QuickAccess no iría acá, solo debería renderizarse abajo del renderContent() de escritorio que se está validando abajo en Home(), esto aplica también para MySavings

2023-10-27 14:50 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
> +              {programmedSavings.length > 0 && (
Tanto en este renderContent del Home como en el de MySavings tenemos estas validaciones que están bien pero no están cubriendo todo lo que deberían, por ejemplo, ese Stack que esta justo después de este código JS se va a renderizar independientemente de que se mapeen los programmedSavings o no, eso deja residuos de código a la hora de presentar el DOM de la aplicación, aprovechemos y corrijamos en los casos que se da

2023-11-03 13:13 UTC, Sebas3245 requested changes

2023-11-03 13:13 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/interface.tsx
> +interface MySavingsUI {
Aca falta el sufijo props

2023-11-03 13:13 UTC, Sebas3245 commented on src/pages/admin/home/interface.tsx
> +            {savingsCommitmentsMock.length &&
No deberiamos validar la existencia de la propiedad length ya que esta si o si existe, el arreglo en si tambien en este momento existe no hay posibilidad de que sea undefined, lo unico que hay que validar es que el length sea mayor a 0

2023-11-03 13:13 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/interface.tsx
> +            {savingsCommitmentsMock.length &&
No deberiamos validar la existencia de la propiedad length ya que esta si o si existe, el arreglo en si tambien en este momento existe no hay posibilidad de que sea undefined, lo unico que hay que validar es que el length sea mayor a 0

2023-11-03 15:16 UTC, Sebas3245 requested changes

2023-11-03 15:16 UTC, Sebas3245 commented on src/pages/admin/savings/MySavings/interface.tsx
> +              investmentsCommitmentsMock.length > 0 && (
Esta validación doble no nos sirve porque puede que tengamos compromisos de ahorro y no de inversión y viceversa, lo ideal sería validar productsCommitments.length

2023-11-03 15:58 UTC, Sebas3245 approved these changes

2023-11-03 15:59 UTC, merged

2023-11-03 15:59 UTC, Sebas3245 commented
solved #311