jg/330/Personal-assets-editing-should-work
selsa-inube/personas pull request #338
Opened 2023-10-27 13:00 UTC by novadeveloper14

2023-10-27 14:39 UTC, CristianRojas-47 approved these changes
el desarrollo del requerimiento es correcto.

2023-10-27 15:28 UTC, Sebas3245 requested changes
Si creo más de un activo y voy a editar el primero que creé se eliminan los demás por algún motivo.

Si decido cancelar la edición en lugar de guardarla, y luego voy a crear un nuevo activo, aparecen los valores del activo que estaba editando, pero cancele y está mal porque se debería resetear el modal así le de cancelar.

Otro caso en el cual tengo dos activos y por ejemplo cambio cualquiera de los campos por ejemplo la cuota, y le doy guardar pues se actualiza bien, pero si le doy editar otra vez, por algún motivo vuelve al valor que tenía al inicio cuando lo cree, es decir se anula la última actualización

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +    const assetToEdit = formik.values.entries.find(
Coloquemos que esta contante sea de tipo " :IPersonalAssetEntry"

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +  const updateAsset = (entry: IPersonalAssetEntry) => {
No es necesario crear esta función, dejemos este código dentro del propio map para no dar peso a renderización de este componente ya que estará presente en todos los registros de la tabla

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +      formik.setValues({
Este setValues dejemosle que entries: formik.values.entries, ...assetToEdit

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +  const getEditAsset = () => {
Esta función la podemos dejar por fuera del componente si le pasamos el objeto formik

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +    fieldsToClear.forEach((field) => formik.setFieldValue(field, ""));
Podemos reemplazar esto por formik.resetForm() pasandole los campos a resetear y el valor "", para no hacer ese forEach ni crear el arreglo anterior

2023-10-27 15:28 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
> +      fieldsToClear.forEach((field) => formik.setFieldValue(field, ""));
Reemplazar esto por formik.resetForm() como se indica en el comentario anterior

2023-10-27 15:28 UTC, Sebas3245 commented on src/components/modals/forms/update-data/AssetModal/index.tsx
> +  onSubmit: () => void;
Mejor que esta propiedad se llame onConfirm

2023-10-28 00:15 UTC, novadeveloper14 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/index.tsx
> +      fieldsToClear.forEach((field) => formik.setFieldValue(field, ""));
El método resetForm de Formik restablece todo el formulario a su estado inicial, lo que incluye borrar y restablecer todos los campos del formulario, incluyendo el campo entries. por eso opte por resetear cada campo individualmente.

2023-10-30 13:12 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +          } else {
No es necesario poner este "else" ya que el if tiene un return y si la condicion se cumple el mapeo pasa al siguiente índice

2023-10-30 13:12 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +    fieldsToClear.forEach((field) => formik.setFieldValue(field, ""));
Entiendo, entonces en su lugar igual no veo tan necesario hacer el forEach si de igual forma vamos a escribir en el código campo por campo (en este caso en el arreglo), por lo tanto, propongo que se use el formik.setValues() y dentro de los paréntesis pasarle cada nombre del campo y el valor ""

2023-10-30 14:07 UTC, novadeveloper14 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/EditAsset/index.tsx
> +    fieldsToClear.forEach((field) => formik.setFieldValue(field, ""));
lo que pasa con formik.setValues() es que en el index.tsx de PersonalAssetsForm al momento de pasarle cada campo y el valor : "", pide tambien el value entries y cuando se le pasa formik.values.entries de todas maneras este campo no almacena las entries.

2023-10-31 02:09 UTC, Sebas3245 approved these changes

2023-10-31 02:09 UTC, merged

2023-10-31 02:10 UTC, Sebas3245 commented
solved #241

2023-11-03 13:32 UTC, Sebas3245 commented
solved #337