jg/396/There-are-required-fields-that-do-not-say-they-are-required
selsa-inube/personas pull request #339
Opened 2023-10-27 14:34 UTC by novadeveloper14

2023-10-30 22:34 UTC, CristianRojas-47 requested changes
Los campos vacíos muestran un mensaje válido, que no debe mostrarse.
![Captura de pantalla 2023-10-30](https://github.com/selsa-inube/personas/assets/93727887/bb84c383-01fd-428e-a10b-6b2c70c32da4)

2023-10-31 13:29 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-10-31 16:25 UTC, Sebas3245 requested changes
Debemos ajustar lo siguiente:

El formulario debe poder validar el required y así mismo mostrar el (Requerido) al lado del label es decir en términos de código tener en true la propiedad isRequired del input solo si el formulario está configurado para que así sea, ya que esto puede ser dinámico dependiendo de una configuración externa que aún no conocemos y que el proyecto recibirá en algún momento, por ello propongo realizar lo siguiente:

- Crear un archivo de configuración con un nombre adecuado que tenga ese objeto de configuración que diga cuales campos son requeridos.
- Debemos buscar la forma de homologar ese objeto dentro del index para que se le añada al esquema de yup a los respectivos campos y también a los respectivos "isRequired" de los inputs.

Tips para la solución:

- Para manipular dinámicamente el esquema de validación podemos crear un estado y sería ideal ya que de momento no sabemos cómo se obtendrá esa configuración externa pero lo más probable es que sea dentro del ciclo de vida del componente
-No debemos dejar de lado las validaciones que ya tenga un campo cambiándolas por él .required en caso de que el campo sea requerido según la configuración, para ello podemos usar el .concat de yup

Cuando este realizado podemos probar con campos requeridos y sin campos requeridos para que el comportamiento sea el esperado en ambos casos es decir que cuando un campo está en la configuración como requerido aparezca la etiqueta (Requerido) y se valide y cuando no, no debe aparecer ni la etiqueta ni debe validar eso.

2023-11-01 14:25 UTC, Sebas3245 requested changes

2023-11-01 14:25 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
> +  const [requiredContactFields, setRequiredContactFields] =
Eliminemos este estado y en su lugar creemos uno llamado dynamicSchema que reciba el esquema inicial y las validaciones de los operadores de si es required o no las saque de contactDataRequiredFields

2023-11-01 14:25 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
> +  const validationSchema = Yup.object().shape({
Dejemos este objeto por fuera del componente

2023-11-01 14:25 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
>    function stateValue(attribute: string) {
Cambiemos esta funcion por la nueva getFieldState global

2023-11-01 14:25 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
Ahora para saber si un campo es requerido o no podemos obtener esa informacion del esquema de yup de la siguiente manera creando una funcion:

const isFieldRequired = (fieldName: string) => {
    return (
      schema
        .describe()
        .fields[fieldName].tests.findIndex(({ name }) => name === "required") >= 0
    );
  }
  
  Habria que pasarle el dynamicSchema a la interfaz y le pasamos esta funcion a cada isRequired de cada campo junto con el nombre del mismo.
 
 Si esa opcion no funciona probar con una como esta:
 
const isRequired = (fieldName): boolean  => {
  const fieldDescription = this.simpleSchema.describe().fields[fieldName] as any;
  return (!fieldDescription.nullable && !fieldDescription.optional);
}

2023-11-02 21:03 UTC, Sebas3245 requested changes

2023-11-02 21:03 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/interface.tsx
> +  schema: ObjectSchema<{}>;
Esta propiedad deberia llamarse valdiationSchema, debido a que solo "schema" no nos dice nada en si

2023-11-02 21:03 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
> +  const [dynamicSchema, setDynamicSchema] = useState(validationSchema);
la idea es que el useFormik reciba este nuevo esquema en lugar del que esta por fuera del componente.

2023-11-03 12:56 UTC, Sebas3245 requested changes

2023-11-03 12:56 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/ContactDataForm/index.tsx
> +      valdiationSchema={dynamicSchema}
validationEsquema* escribi mal cuando le puse el comentario

2023-11-03 15:11 UTC, Sebas3245 approved these changes

2023-11-03 15:11 UTC, merged