Cr/397/adjust empty non required field is not valid
selsa-inube/personas pull request #343
Opened 2023-10-30 16:38 UTC by CristianRojas-47

2023-10-31 06:57 UTC, novadeveloper14 approved these changes

2023-11-07 17:14 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2023-11-07 18:15 UTC, Sebas3245 requested changes

2023-11-07 18:15 UTC, Sebas3245 commented on src/design/input/TextField/interface.tsx
> +      {state === "valid" && inputValue && inputValue.toString().length > 0 && (
¿No tendría el mismo efecto si acá en lugar de inputValue ponemos el "value" que llega como prop? es decir para no tener que crear un nuevo estado interno

2023-11-07 22:48 UTC, Sebas3245 requested changes

2023-11-07 22:48 UTC, Sebas3245 commented on src/mocks/users/users.mocks.tsx
> +        city: "Medellín",
¿Porque paso estos valores a value y no como estaban en id? lo que pasa es que ese city es un dominio y la idea es extraerlo como se esta haciendo actualmente en ContactDataForm

2023-11-07 22:49 UTC, Sebas3245 commented on src/mocks/users/users.mocks.tsx
> +        city: "Medellín",
Sería bueno que consulte con Leonardo si ese campo ciudad en ContactData debería ser un select con autocompletado (que yo creería que sí) en lugar de un Textfield

2023-11-08 23:02 UTC, Sebas3245 approved these changes

2023-11-08 23:02 UTC, merged

2023-11-08 23:02 UTC, Sebas3245 commented
solved #328