Cr/363/adjust edit button of personal debts form
selsa-inube/personas pull request #350
Opened 2023-11-01 20:29 UTC by CristianRojas-47

2023-11-01 23:07 UTC, novadeveloper14 approved these changes
el desarrollo es correcto

2023-11-02 20:57 UTC, Sebas3245 requested changes

2023-11-02 20:57 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
> +      const fieldsToClear = [
Cambiemos este fields to clear y luego recorrerlo por un formik.setValues colocando cada campo aqui mencionado en  string vacio "", esto en los  modales

2023-11-02 20:57 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalDebtsForm/index.tsx
> +    const fieldsToClear = [
Cambiemos este fields to clear y luego recorrerlo por un formik.setValues colocando cada campo aqui mencionado en  string vacio "", esto en los  modales

2023-11-02 20:57 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalDebtsForm/EditDebt/index.tsx
> +    const fieldsToClear = [
Cambiemos este fields to clear y luego recorrerlo por un formik.setValues colocando cada campo aqui mencionado en  string vacio "", esto en todos los casos donde se esta haciendo de la misma manera, tambien en assets y debts

2023-11-03 21:04 UTC, Sebas3245 approved these changes

2023-11-03 21:04 UTC, merged

2023-11-03 21:06 UTC, Sebas3245 commented
solved #333