sl/412/mock-income-step
selsa-inube/personas pull request #355
Opened 2023-11-07 23:38 UTC by Sebas3245

2023-11-10 13:33 UTC, novadeveloper14 requested changes
1. el paso en general en todo el desarrollo debería llamarse incomes no icome

2. al llenar los datos, avanzar y devolverme de otro paso, el total de gastos reportados cambia su valor a $0.00.

3. por alguna razón los campos que están vacíos están activando el mensaje de validación

4. deberíamos preguntarle a Leonardo si alguno de los campos puede ser requerido dependiendo el cliente que lo solicite y si es así manejar el tema de las validaciones dinámicas y el archivo de los campos requeridos. como se hizo en ContactDataForm.

2023-11-22 15:33 UTC, Sebas3245 commented
En cuanto al primer punto de corrección, la traduccion es "income" para "ingresos"

En cuanto al último punto si bien ya tenemos otro paso con esa implementación y de momento no estamos 100% que así se va a manejar en todos los pasos, de momento dejémoslos así y tal vez más adelante cuando tengamos clara esa información del negocio podemos implementarla

2023-11-23 01:47 UTC, novadeveloper14 requested changes
me refería a que debería ser "incomes" en plural ya que el paso se llama ingresos no ingreso por lo que debería de ser modificado en todo el desarrollo.

2023-11-23 01:48 UTC, Sebas3245 commented
@novadeveloper14 ingresos en plural en inglés es "income"

2023-11-23 01:51 UTC, novadeveloper14 commented
@Sebas3245 
![image](https://github.com/selsa-inube/personas/assets/87447257/72800c69-262c-49ac-a426-ba115b51dc0c)
creo que income es el singular y incomes es el plural

2023-11-23 13:02 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2023-11-23 13:03 UTC, merged