jg/411/Mock-Actividad-economica-step
selsa-inube/personas pull request #359
Opened 2023-11-22 07:21 UTC by novadeveloper14

**Funcionalidades especiales a tener en cuenta en el momento de la revisión**

- Se implemento el modal para las actividades CIIU cuando se le da click al icono de la lupa.
 
- Se realizo la funcionalidad para que el campo de Empresa (company) tenga un autocompletado el cual si se selecciona una empresa del autocompletado NO muestra los campos extra que requieren información detallada sobre la empresa.

2023-11-22 22:45 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-11-23 23:51 UTC, Sebas3245 requested changes
Revisar los siguientes puntos encontrados:

1. Si yo aún no he escrito nada en el modal de búsqueda de actividad económica, pero hago click sobre el TextField, directamente aparecen las opciones, lo cual creo que no debería ya que deben salir solo las que yo escriba, esto teniendo en cuenta que no sabemos cuántas pueden ser a futuro y sería un gran peso mostrarlas todas desde el inicio cuando hago click en el input

2. Al filtrar una actividad económica en el modal de búsqueda de actividad económica está siendo sensitivo a mayúsculas y minúsculas, y esto está mal porque si busco por ejemplo "Profesionales" no me aparece porque en la opción esa palabra está en mayúscula, debería encontrarlo y no ser sensitivo al case

3. Veo que falta la sección "Detalles laborales" en el formulario, ¿es por algún motivo en específico?

2023-11-23 23:51 UTC, Sebas3245 commented on src/components/modals/forms/update-data/economicActivityModal/index.tsx
> +      return (
Esta función debería funcionar sin el return, es decir después del arrow sin corchetes colocar lo de activity.id....etc

Es solo un ajuste de acortar codigo aprovechando que el arrow tiene el return implicito

2023-11-23 23:51 UTC, Sebas3245 commented on src/components/modals/forms/update-data/economicActivityModal/index.tsx
> +              cursorHover={true}
No es necesario pasarle el valor true, solo colocar cursorHover y ya

2023-11-23 23:51 UTC, Sebas3245 commented on src/components/modals/forms/update-data/economicActivityModal/index.tsx
> +          ></TextField>
Aca se le fue la etiqueta de cierre

2023-11-23 23:51 UTC, Sebas3245 commented on src/components/modals/forms/update-data/economicActivityModal/styles.ts
> +const StyledDivider = styled.hr<IStyledDivider>`
Ya existe un componente "Divider" para no tener que crearlo a mano varias veces

2023-11-23 23:51 UTC, Sebas3245 commented on src/design/input/TextField/interface.tsx
> +    handleIconClick,
Recibámosla como "on"

2023-11-23 23:51 UTC, Sebas3245 commented on src/design/input/TextField/index.tsx
> +    handleIconClick,
Recibámosla como "on"

2023-11-23 23:51 UTC, Sebas3245 commented on src/mocks/domains/companies.ts
> +const CompaniesData = [
Debe declararse en camelCase, no en PascalCase

2023-11-23 23:51 UTC, Sebas3245 commented on src/mocks/domains/companies.ts
> +const CompaniesData = [
Revisar donde mas se puede estar dando esto

2023-11-23 23:51 UTC, Sebas3245 commented on src/mocks/users/economicActivities.tsx
> +
El nombre de este archivo deberia tener el .mocks.ts.

Y seria .ts porque no tiene codigo JSX, es importante tener esto presente en todos los desarrollos ya que es clave para la lectura del codigo

2023-11-23 23:51 UTC, Sebas3245 commented on src/mocks/users/users.mocks.tsx
> +    economicActivity: {
Todo esto deberia validarse dentro de un map es decir que este economic Activity sea una propiedad opcional de IThird y dentro del map se valida si el usuario lo tiene para dejar valores vacios, ya que se ve feo dejar valores vacios dentro del mock

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/companyFormalitydm.ts
> +
El nombre del archivo no deberia estar en pascal case, digamos que es un estandar de dominios dejarlo todo en minuscula

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/companyFormalitydm.ts
> +
Revisar en que otros casos esta pasando esto en el desarrollo

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/dependencedm.ts
> +
Este dominio dejemoslo dentro de mocks/domains siento que son datos muy configurables de LINIX

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/economicSectordm.ts
> +
Este dominio dejemoslo dentro de mocks/domains siento que son datos muy configurables de LINIX

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/positiondm.ts
> +
Este dominio dejemoslo dentro de mocks/domains siento que son datos muy configurables de LINIX

2023-11-23 23:51 UTC, Sebas3245 commented on src/model/domains/economicActivity/professiondm.ts
> +
Este dominio dejemoslo dentro de mocks/domains siento que son datos muy configurables de LINIX

2023-11-23 23:51 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
> +  handleSubmit?: (values: IEconomicActivityEntry) => void;
Dejemosla como "on"

2023-11-23 23:51 UTC, Sebas3245 commented on src/validations/validationRules.ts
> +  employeeCode: Yup.string()
Esta dejemosla a mano donde se requiere, no me parece que sea una validacion general

2023-11-23 23:51 UTC, Sebas3245 commented on src/validations/validationRules.ts
> +  job: Yup.string()
Esta dejemosla a mano donde se requiere, no me parece que sea una validacion general

2023-11-23 23:51 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
> +  const [dynamicSchema, setDynamicSchema] = useState(validationSchema);
Porque se está usando un schema dinamico? el setDynamicSchema no se esta usando

2023-11-23 23:51 UTC, Sebas3245 commented on src/components/modals/forms/update-data/economicActivityModal/index.tsx
El nombre de este archivo esta en camelCase, deberia estar en PascalCase como todos los componentes que creamos, revisar si sucede en alguna otra parte del desarrollo

2023-11-24 06:04 UTC, novadeveloper14 commented on src/pages/general/UpdateData/forms/EconomicActivityForm/index.tsx
> +  const [dynamicSchema, setDynamicSchema] = useState(validationSchema);
así esta igual que en contactDataForm, habías dicho que ese setDynamicSchema se usaría cuando un cliente le diga a la aplicación que campos del formulario iban a a ser requeridos y cuales no. así manejarlo dinámicamente atreves de ese estado.

2023-11-24 16:49 UTC, Sebas3245 approved these changes

2023-11-24 16:49 UTC, merged