feat(familyGroup): create familyGroup step and family member view
selsa-inube/personas pull request #372
Opened 2023-11-29 02:18 UTC by CristianRojas-47

2023-11-29 14:36 UTC, novadeveloper14 requested changes

2023-11-29 14:36 UTC, novadeveloper14 commented on src/pages/general/UpdateData/config/mappers.ts
> +    relationship: relationshipDM.valueOf(
acá debería dejar que se le pase el id y ya internamente en el modal eliminar la `const selectedRelationship` y al campo pasarle `formik.values.relationship` y en la tabla los datos que se le están pasando si pasarle la modificación usando el `relationshipDM.valuesOf(...)?.value`

2023-11-29 14:36 UTC, novadeveloper14 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/config/table.tsx
> +const familyGroupTableBreakpoints = [
la tabla de resoluciones(X) 1020px a 1210px aprox esta recortando las acciones.

2023-11-29 14:36 UTC, novadeveloper14 commented on src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
ahora mismo este modal cuando aparece esta generando un scroll en pantalla. hablar con Leonardo si este comportamiento debería ser así o es mas factible ponerle un max-height a el modal y hacer que tenga un scroll interno como por ejemplo esta en el modal de actividades. pienso esto ya que para que el usuario llegue a identificar que existen los botones de abajo de eliminar y editar se da cuenta hasta que haga el scroll down completamente.

2023-11-30 05:40 UTC, novadeveloper14 approved these changes

2023-11-30 13:44 UTC, Sebas3245 requested changes
Aunque el modal se ve bien en estilos, estoy viendo que esta quedando muy pegado a la parte de arriba:

![image](https://github.com/selsa-inube/personas/assets/55991750/582687f5-fda9-4c7c-9888-d7d2ee020e24)


Sería bueno dejar una separación, como en el figma: 

![image](https://github.com/selsa-inube/personas/assets/55991750/0ca274a8-2fb5-4d58-b5f0-367f476e8314)

2023-11-30 13:44 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/index.tsx
> +  const familygroupTableActions: IAction[] = [
family group son dos palabras aparte, hay que corregir eso en el nombre de este objeto y en las propiedades en las que tambien este mal ese camel

2023-11-30 13:44 UTC, Sebas3245 commented on src/model/entity/user.ts
> +    fullName?: string;
No creemos esta propiedad, este es un dato que se puede armar a mano donde se requiera, se puede armar dentro de un mapper unico dentro de src\pages\general\UpdateData\forms\FamilyGroupForm\config esclusivo para la tabla de grupo familiar

2023-11-30 13:44 UTC, Sebas3245 commented on src/design/input/Select/interface.tsx
> +          value={currentOption?.value || value || ""}
No hagamos este ajuste, entiendo el problema que se presenta al quitarlo pero dejar valores inconclusos en un campo de seleccion puede traer problemas, por ende propongo lo siguiente, en el mapFamilyGroup no hacer ningun valueOf.id ya que de por si lo que esta llegando ya deberia ser el id, mocks:

![image](https://github.com/selsa-inube/personas/assets/55991750/4ca77efe-2898-4d83-ab56-299ddac594e4)


Ahora bien, con esto en el modal va a aparecer correctamente el valor en el select pero en la tabla no, por ende podemos crear un mapper esclusivo para esa tabla en src\pages\general\UpdateData\forms\FamilyGroupForm\config en el cual si le hagamos el respectivo valueOf a la propiedad "?.value" para asi mostrar el valor correcto en la tabla y tambien el fullName, este nuevo mapper deberia retornar un tipo "IEntry[]" y con este mapper envolvemos el formik.values.entries de la propiedad entries de la Table

2023-11-30 13:44 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
> +                    value={formik.values.isDependent ? "Y" : "N"}
No usemos estos string quedamos para "Y" y "N" usemos activeDM.Y y activeDM.N

2023-12-01 12:55 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
> +                cursorHover={true}
Aun hay varias partes del desarrollo donde esta sucediendo esto
![image](https://github.com/selsa-inube/personas/assets/55991750/5d38194a-146c-4185-b4f1-a359c542b472)

2023-12-01 12:59 UTC, Sebas3245 requested changes

2023-12-01 12:59 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/config/mapper.ts
> +const mapFamilyGroupForTable = (entries: IFamilyGroupEntry[]): IEntry[] => {
Cambiemos el nombre a mapFamilyGroupTable nada mas

2023-12-01 15:36 UTC, Sebas3245 requested changes
Aun falta resolver esto:
![image](https://github.com/selsa-inube/personas/assets/55991750/0a83c6be-5710-448c-9ebd-2311195a8f06)

2023-12-01 21:44 UTC, Sebas3245 approved these changes

2023-12-01 21:44 UTC, merged