jg/453/Adjust-the-verification-of-the-fields-on-Update-Data
selsa-inube/personas pull request #386
Opened 2023-11-30 17:56 UTC by novadeveloper14

Lo que estaba pasando es que en las funciones de estado de los campos que se pasa a la prop state se estaba retornando "valid" pero según lo hablado con @LoweLeo esto solo es una funcionalidad para formularios que se están diligenciando desde cero, el cual no es el caso de el formulario asistido de la actualización de datos que son datos que ya estaban desde un principio.

Opte por crear una función general en las utilidades de los formularios la cual manejara el estado del campo sin retornar el estado "valid" entonces ya se manejaran estas dos opciones getFieldState y getFieldStateUpdateData dependiendo el tipo de formulario que se esta diligenciando.

2023-11-30 19:33 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-11-30 19:56 UTC, Sebas3245 requested changes

2023-11-30 19:56 UTC, Sebas3245 commented on src/utils/forms.tsx
> +const getFieldStateUpdateData = (formik: FormikValues, fieldName: string) => {
Esta funcion tiene un nombre muy puntual (update data) como para dejarlo asi en algo tan general como lo es utils/forms.tsx, cambie el nombre a algo mas generico y que aparte se pueda aprovechar en otras partes de la aplicacion como "getNoValidFieldState"

2023-12-01 12:52 UTC, Sebas3245 commented on src/utils/forms.tsx
> +const getModifiedFieldState = (formik: FormikValues, fieldName: string) => {
La idea es no tener que crear esta funcion nueva si no que se aplique sobre el "getFieldState" o donde sera necesario el ajuste del no mostrar el valid si se hizo blur sin cambiar nada, pero esto debe aplicar ya para todos los TextField del proyecto, otra cosa a tener en cuenta es que aunque este ajuste de esta funcion lo esta solucionando relativamente, esta pasando que si yo por ejemplo hago click sobre un Textfield y no lo cambio y hago blur todo bien no aparece el valid, pero si luego cambio el texto del campo esta apariendo el valid en el evento onChange y no deberia, ese valid solo debe aparecer en el blur y solo si se hizo un cambio en el contenido del Textfield

2023-12-01 15:48 UTC, merged