jg/460/Adjust-behavior-and-autocomplete-of-contactDataForm-fields
selsa-inube/personas pull request #397
Opened 2023-12-01 00:07 UTC by novadeveloper14

2023-12-01 16:11 UTC, CristianRojas-47 approved these changes
el desarrollo del requerimiento es correcto.

2023-12-01 16:54 UTC, Sebas3245 requested changes

2023-12-01 16:54 UTC, Sebas3245 commented on src/design/input/DropdownMenu/index.tsx
> +            onClick={() => handleOptionClick(dropDownItem.value)}
Si o si debemos manejar los valores con el id no con el value

2023-12-01 20:02 UTC, novadeveloper14 commented on src/model/domains/personalInformation/citydm.ts
> +    value: "Bogotá",
se va a dejar como Bogotá D.C

2023-12-01 21:28 UTC, Sebas3245 requested changes
En el paso de verificacion estan saliendo los id en lugar del valor

2023-12-04 17:38 UTC, Sebas3245 approved these changes

2023-12-04 17:39 UTC, merged

2023-12-04 17:39 UTC, Sebas3245 commented
solved #385