jg/462/Adjust-the-design-of-the-Modals
selsa-inube/personas pull request #401
Opened 2023-12-01 18:19 UTC by novadeveloper14

2023-12-04 19:12 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-05 12:40 UTC, Sebas3245 requested changes

2023-12-05 12:40 UTC, Sebas3245 commented on src/components/modals/forms/update-data/EconomicActivityModal/index.tsx
> +  const smallScreen = useMediaQuery("(max-width: 550px)");
Cambiemos este smallScreen por isMobile, pero solo en esta constante

2023-12-05 12:40 UTC, Sebas3245 commented on src/components/modals/forms/update-data/RelationshipWithDirectorsModal/index.tsx
> +  const smallScreen = useMediaQuery("(max-width: 550px)");
cambiemos a isMobile

2023-12-05 14:09 UTC, merged

2023-12-05 14:09 UTC, Sebas3245 commented
solved #391