fix(bankTransferForm): adjust the behavior of the gap
selsa-inube/personas pull request #403
Opened 2023-12-01 19:52 UTC by CristianRojas-47

Hablando con Leonardo, él me indicó que no es necesario tener dos columnas, sino que se puede pasar de tres columnas a una sola; mencionó que la división en dos columnas se utiliza cuando el formulario tiene muchos campos.

2023-12-01 20:18 UTC, novadeveloper14 approved these changes

2023-12-01 21:31 UTC, Sebas3245 requested changes

2023-12-01 21:31 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/BankTransfersForm/interface.tsx
> +          isMobile ? "1fr" : isTablet ? "1fr" : "1fr 1fr 1fr"
Segun el comentario que dejo entonces aca no seria necesario la validacion del isMobile, ya que con el solo isTablet a partir de esos px para abajo siempre colocara una sola

2023-12-01 22:24 UTC, Sebas3245 approved these changes

2023-12-05 12:41 UTC, merged

2023-12-05 12:42 UTC, Sebas3245 commented
solved #389