jg/408/Mock-editing-a-relative-in-family-group-step
selsa-inube/personas pull request #425
Opened 2023-12-11 15:30 UTC by novadeveloper14

2023-12-12 20:31 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-12 22:45 UTC, Sebas3245 requested changes
En general revisar el desarrollo de acuerdo a los puntos de código que se indicaron ya que pueden estar sucediendo en otras partes del código y no solo donde las mencione

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/config/tabs.ts
> +const editFamilyMemberModalTabs = [
Creese una interfaz global para este tipo de estructura de tabs, puede ponerla en los types del componente tabs y la idea seria que el isDisabled sea opcional para no tener que estar pasandole el isDisabled: false siempre que se añade un item al array

2023-12-12 22:45 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/interface.tsx
> +        cursorHover={true}
No es necesario el = {true}

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
> +              cursorHover={true}
No es necesario el = {true}

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
> +              appearance="dark"
La apariencia por defecto del Text es dark

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
> +              <TextField
Manejemos estos datos como type="number" y en el value le puede colocar || "" para que no le arroje error de input no controlado, esto aplica para telefonos, cedulas y demas campos que realmente seria necesario que no deje escribir un numero al usuario

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/styles.ts
> +const StyledDivider = styled.hr<IStyledDivider>`
Recuerde que ya existe un componente Divider

2023-12-12 22:45 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
> +                  formik.values.isDependent === activeDM.Y.id
isDependent es un booleano no un valor de "Y" o "N"

2023-12-12 22:45 UTC, Sebas3245 commented on src/design/navigation/Tab/index.tsx
> +interface ITabProps {
Corregir los nombres de las interfaces, entiendo que se trajo el componente de design-system pero no hay que perder los estandares que tenemos nosotros, aparte poner la interfaz justo arriba del componente

2023-12-12 22:45 UTC, Sebas3245 commented on src/design/navigation/Tab/stories/Tab.stories.tsx
> +const Default = (args: ITabProps) => <TabController {...args} />;
Usar StoryFn para que en el objeto args le autocomplete y corrija las propiedades, esto es mas una buena practica para identificar las propiedades que hemos aplicado en otros story de otros componentes

2023-12-12 22:45 UTC, Sebas3245 commented on src/design/navigation/Tab/stories/TabController.tsx
> +  const [tabSelected, setTabSelected] = useState(false);
cambiemos este estado a "selectedTab"

2023-12-12 22:45 UTC, Sebas3245 commented on src/design/navigation/Tab/stories/TabController.tsx
> +  const onClickTab = () => {
handleClickTab

2023-12-12 22:45 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/index.tsx
> +interface EditFamilyMemberProps {
Colocar justo arriba del componente

2023-12-12 22:45 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/EditFamilyMember/interface.tsx
> +  closeModal: () => void;
onCloseModal

2023-12-13 21:14 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/EditFamilyMemberModal/index.tsx
> +                  formik.values.isDependent === activeDM.Y.id
Aun falta corregir este punto, la idea es que se haga algo como formik.values.isDependent ? activeDM.Y.id : activeDM.N.id, ya que como comente esa propiedad es un booleano y si no lo es en alguna parte entonces hay que ajustarlo para que lo sea

2023-12-14 23:43 UTC, Sebas3245 requested changes
Los campos como celular, email y fecha de nacimiento no estan ejecutando validaciones, me permite colocar los datos en formatos incorrectos, revisar en estos y en los demas campos

2023-12-18 18:34 UTC, Sebas3245 approved these changes

2023-12-18 18:34 UTC, merged