feat(savings): add Mock page for requesting a savings product
selsa-inube/personas pull request #431
Opened 2023-12-14 18:42 UTC by ANGIECATHERINEP

2023-12-14 20:40 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-14 23:47 UTC, Sebas3245 requested changes

2023-12-14 23:47 UTC, Sebas3245 commented on src/components/cards/RequestCard/index.tsx
> +            if (Object.entries(descriptions).length > 1) {
Podrias hacer esta validacion con un operador ternario y dentro de <Stack gap="s100" key={index}>

2023-12-15 13:23 UTC, Sebas3245 requested changes

2023-12-15 13:23 UTC, Sebas3245 commented on src/components/cards/RequestCard/index.tsx
> +  let descriptionsLength = Object.entries(descriptions).length > 1;
Esto podria ser una constante ya que su valor no cambiara nunca una vez se inicia el componente y se podria llamar "withListIndicators"

2023-12-15 14:21 UTC, Sebas3245 approved these changes

2023-12-15 14:22 UTC, merged