feat(cdatRequest): create mock inversión step for requesting a cdat
selsa-inube/personas pull request #434
Opened 2023-12-15 16:10 UTC by ANGIECATHERINEP

2023-12-18 20:22 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-19 13:30 UTC, Sebas3245 requested changes
Tambien olvide comentarte algo y es que a cualquier paso que se haga hay que hacerle tambien su paso de verificacion/resumen por ende hay que crear ese paso y añadirle los datos de inversion

2023-12-19 13:30 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/config/assisted.ts
> +    let newcdatRequest = { ...currentcdatRequest };
aca seria newCdatRequest

2023-12-19 13:30 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/config/assisted.ts
> +    if (!stepKey) return currentcdatRequest;
currentCdatRequest

2023-12-19 13:30 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/config/navigation.ts
> +const crumbsCdatRequest = [
Tratemos de dejar estos Cdat como CDAT excepto cuando se empieza con esa palabra por ejemplo si fuera cdatRequest si se deja asi en minuscula

2023-12-19 13:30 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
> +  function stateValue(attribute: string) {
Usemos la funcion getStateValue que esta en utils/forms

2023-12-19 13:30 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
> +  const handleChangeWithCurrency = (e: React.ChangeEvent<HTMLInputElement>) => {
Pasemos esta funcion y la de validateCurrencyField a utils/forms.tsx a ver si las podemos generalizar (deben recibir el objeto formik)

2023-12-19 23:02 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
> +  function stateValue(attribute: string) {
Falta este ajuste

2023-12-19 23:02 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/InvestmentForm/interface.tsx
> +  function stateValue(attribute: string) {
Creo que se llama getFieldState

2023-12-19 23:04 UTC, Sebas3245 requested changes

2023-12-20 13:09 UTC, Sebas3245 approved these changes

2023-12-20 13:09 UTC, merged