jg/489/Generate-Manifest-for-plugin-PWA-with-assets
selsa-inube/personas pull request #439
Opened 2023-12-19 14:53 UTC by novadeveloper14

2023-12-19 21:14 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-19 22:39 UTC, Sebas3245 requested changes

2023-12-19 22:39 UTC, Sebas3245 commented on manifest.js
Podríamos ponerle manifest.ts?

2023-12-19 22:39 UTC, Sebas3245 commented on manifest.js
> +    description: "Personas Description",
Aca coloquemosle "Portal de clientes"

2023-12-19 22:39 UTC, Sebas3245 commented on manifest.js
> +const manifestForPlugIn = {
A esta constante llamemosla manifestPWA

2023-12-20 07:05 UTC, novadeveloper14 commented on manifest.js
el problema es que en tsconfig.json solo se estan incluyendo los archivos que estan adentro de la carpeta src, TypeScript no lo reconocerá como parte del proyecto y no lo compilará por eso creo que es mejor dejarlo como js

2023-12-20 13:48 UTC, Sebas3245 commented on manifest.js
Entiendo, en ese caso podriamos poner el manifest.ts en el include a la par de src?

2023-12-20 21:13 UTC, Sebas3245 approved these changes

2023-12-20 21:13 UTC, merged