Ap/499/mock condiciones step for cdat
selsa-inube/personas pull request #448
Opened 2023-12-26 18:33 UTC by ANGIECATHERINEP

2023-12-27 22:59 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-12-28 15:51 UTC, Sebas3245 requested changes

2023-12-28 15:51 UTC, Sebas3245 commented on src/design/data/Table/index.tsx
> +  const columnActions = actions ? true : false;
cambiemos el nombre de esta constante a  "withActions" tambien en TableUI el nombre de la propiedad

2023-12-28 15:51 UTC, Sebas3245 commented on src/design/data/Table/index.tsx
> +        actions={actions!}
Volvamos esta propiedad actions opcional en TableUI para no tener que usar este operador "!"

2023-12-28 15:51 UTC, Sebas3245 commented on src/design/data/Table/interface.tsx
> +  if (breakpoints) {
Aca esta condicion no esta haciendo mucho realmente, hay que tener en cuenta que breakpoints no es opcional por ende nunca podra ser null o undefined, por lo tanto no seria necesario ponerla, si llega undefined es porque tenemos mal el codigo usando esos operadores "!"  burlando asi lo que hace typescript por nosotros, porfa quitalos para que esto no suceda  
![image](https://github.com/selsa-inube/personas/assets/55991750/21a22ab9-e9d4-4075-ac0f-42caf0373cb2)

solo seria poner las propiedades como opcionales "?" y en el caso de esta condicion seria no hacerla ya que es una mala practica declarar hooks dentro de condicionales, lo que podriamos ahcer es validar que si este breakpoints asi : 

const queriesArray = breakpoints && useMemo(
      () => breakpoints.map((breakpoint) => breakpoint.breakpoint),
      [breakpoints]
    );
    
    con eso queriesArray sera string[] | undefined y solo habria que validar su existencia donde sea necesario

2023-12-28 15:51 UTC, Sebas3245 commented on src/design/data/Table/interface.tsx
> +  let TitleColumns = titles;
Podriamos convertir esto a constante, y dejarlo justo debajo de los hooks antes del return para hacerlo asi:  

const titleColumns = useMemo(
      () => totalTitleColumns(titles, breakpoints, media),
      [titles, breakpoints, media]
    );
    
  Importante que el nombre de la constante empiece en minuscula es decir en camelCase

2023-12-28 15:51 UTC, Sebas3245 commented on src/model/entity/product.ts
> +interface IRates {
Seria IRate, tengamos en cuenta que si es una estructura de un objeto unico seria en singular, caso contrario en el caso de que tuvieramos por ejemplo una variable en la cual se almacenara un arreglo de este tipo pues se llamara "rates" y seria de tipo IRate[], o si por ejemplo la estructura guardara un listado o varios listados en si, en ese caso si podria llamarse IRates, en plural, pero en este caso si seria IRate

2023-12-28 15:51 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
> +  const removeLastCharacters = (
Esta funcion podria ir por fuera del componente?

2023-12-29 12:39 UTC, Sebas3245 commented on src/design/data/Table/index.tsx
> +  const withActions = actions ? true : false;
Esto se puede simplificar convirtiendo actions a un boolean asi "const withActions = !!actions"

2023-12-29 12:40 UTC, Sebas3245 commented on src/design/data/Table/index.tsx
> +        actions={actions!}
Aun faltaria corregir aca para que no este el operador "!" al final

2024-01-02 22:03 UTC, Sebas3245 requested changes
Adicionalmente hacer pull de main para corregir conflictos en los cambios de los utils generales

2024-01-02 22:03 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/ConditionsForm/index.tsx
> +      } else {
Este else lo podriamos omitir dejando como valor inicial Number(formik.values.deadlineDays) en "let deadlineDays", asi solo mutaremos su valor en un if sin necesidad de un else ya que seria el valor por defecto

2024-01-05 13:59 UTC, Sebas3245 commented on src/mocks/products/investments/investmentsRates.mocks.ts
> +    AnnualEffectiveRate: "12.55%",
Aca iria camelCase

2024-01-10 12:23 UTC, ANGIECATHERINEP commented on src/mocks/products/investments/investmentsRates.mocks.ts
> +    AnnualEffectiveRate: "12.55%",
En la validación de plazo en número de días la cantidad ingresada debe ser mayor o igual a 30 días, ya cambie el mensaje para que sea más claro

2024-01-10 12:40 UTC, Sebas3245 approved these changes

2024-01-10 12:41 UTC, merged