jg/500/Mock-Reembolso-step-requesting-CDAT
selsa-inube/personas pull request #456
Opened 2024-01-03 13:07 UTC by novadeveloper14

2024-01-03 23:20 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-01-04 13:42 UTC, Sebas3245 requested changes

2024-01-04 13:42 UTC, Sebas3245 commented on src/mocks/domains/refundAccount.ts
¿Porque esta creando un dominio para estos datos?

Son datos personales de un usuario en especifico, no para toda la aplicacion

2024-01-04 13:42 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
> +          label="Forma de reembolso:"
Estos valores de los BoxAttribute no deben ir quemados, hay que deducirlos

2024-01-05 12:33 UTC, Sebas3245 commented on src/mocks/domains/refundAccount.ts
.

2024-01-05 13:09 UTC, Sebas3245 requested changes

2024-01-05 13:09 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
> +                usersMock[0].bankTransfersAccount.bankEntity,
No podemos pasarle el valor del mock porque cuando exista otro usuario va a traer los datos este especificamente, hay que setear esa entidad bancaria cuando se haga la seleccion en el formulario para que quede guardado en los values y colocarlo aca.

2024-01-05 13:09 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
> +                usersMock[0].bankTransfersAccount.accountType,
Aca aplicaria lo mismo que el comentario anterior

2024-01-05 13:09 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/Summary/SummaryBoxes/index.tsx
> +            value="Transferencia cuenta externa"
Aca coloquemosle tambien  el value respectivo de refundMethod con el dominio, esto con el fin de que si el dia de mañana ese texto cambia pues aca no este quemado

2024-01-16 14:04 UTC, Sebas3245 requested changes

2024-01-16 14:04 UTC, Sebas3245 commented on src/pages/request/savings/CdatRequest/forms/RefundForm/index.tsx
> +  }, [savingOptions, formik.values.refundMethod]);
Hay forma de hacer esto solo cuando se inicia el componente es decir con el arreglo de dependencias vacio [], con el fin de que no se refresque el componente con esas condiciones

2024-01-22 13:46 UTC, Sebas3245 approved these changes

2024-01-22 13:46 UTC, merged