jg/495/Print-real-credit-products-of-logged-in-users-in-my-credits
selsa-inube/personas pull request #470
Opened 2024-01-05 20:24 UTC by novadeveloper14

2024-01-10 15:10 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-01-10 17:03 UTC, Sebas3245 requested changes
Si alguien entra a /my-credits a traves de la url sin pasar por el home no le van a cargar los creditos, debe validar esto y hacer el getCreditsForUser en caso de que esto suceda, recordar que esta PR debe salir hoy ya que se mostrara el día de mañana a Fondecom

2024-01-11 12:53 UTC, Sebas3245 requested changes

2024-01-11 12:53 UTC, Sebas3245 commented on src/pages/admin/credits/MyCredits/index.tsx
> +      getCreditsForUser(user?.identification, accessToken)
Antes de hacer o no el fetch la idea es validar que no haya creditos en el context de credits.

2024-01-11 13:24 UTC, Sebas3245 approved these changes

2024-01-11 13:25 UTC, merged