jg/530/Capitalize-username-in-Home-and-User
selsa-inube/personas pull request #471
Opened 2024-01-07 07:46 UTC by novadeveloper14

…etter

2024-01-09 16:22 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-01-09 17:59 UTC, Sebas3245 requested changes

2024-01-09 17:59 UTC, Sebas3245 commented on src/utils/texts.ts
> +  var words = text.split(" ");
usemos const si los valores no van a cambiar dentro de la variable

2024-01-09 17:59 UTC, Sebas3245 commented on src/utils/texts.ts
> +  var capitalizedWords = words.map(function (word) {
Use una arrow parea no tener que hacer el return

2024-01-10 12:00 UTC, Sebas3245 approved these changes

2024-01-10 12:00 UTC, merged

2024-01-10 12:00 UTC, Sebas3245 commented
Solved #462