Ap/517/mock reimbursement step for programmed saving fixed
selsa-inube/personas pull request #483
Opened 2024-01-12 12:12 UTC by ANGIECATHERINEP

2024-01-12 21:27 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-01-12 22:03 UTC, Sebas3245 requested changes

2024-01-12 22:03 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
> +  const valueReimbursement = formik.values.reimbursementType;
Johan para solucionar esto de esa descripcion la añadio directamente al user.mock:

![image](https://github.com/selsa-inube/personas/assets/55991750/70db569d-6a7e-4975-9da4-616ce6998c19)

Me parece que es mejor realizarlo de esa forma ya que es un dato que de momento no sabemos en el back-end como se arma o si nos llegara asi tal cual

2024-01-12 22:03 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/index.tsx
> +          // customHandleChange={customHandleChange}
Hay que eliminar esta linea

2024-01-15 14:45 UTC, Sebas3245 requested changes
Hay un espacio en blanco en el contenido de la cuenta externa:
![image](https://github.com/selsa-inube/personas/assets/55991750/ec3621f7-25f1-4036-90f5-8cbe05bd3221)

Aparte debemos validar las siguientes situaciones: 
1. Un usuario puede tener mas de una cuenta interna/ahorros como se ve en savingsMock las que son de tipo "CA" son de ahorros, en ese caso hay que hacer lo siguiente, si hay mas de una cuenta de AHORROS, debe dejar al usuario seleccionar cual es la cuenta a la que se le va a depositar en el select, mientras que si solo tiene una si debe seleccionarla automaticamente el sistema y dejarla readonly como esta actualmente en tu desarrollo.

2. Si el usuario no tiene ninguna cuenta externa no debe aparecer la opcion de cuenta externa en el select de "Forma de reembolso" y viceversa si por ejemplo no tiene ninguna cuenta interna tampoco deberia aparecer la opcion (hablar con leonardo de que se deberia mostrar si no tiene ni cuenta externa (es decir que el usuario no ha actulizado ese dato) ni tiene cuentas internas es decir cuentas de ahorro aun).

2024-01-15 14:45 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/interface.tsx
> +            (formik.values.accountReimbursement =
No asignemos aca el valor a formik.values.accountReimbursement, hagamoslo mejor en la funcion buildReimbursementAccount antes de cada return

2024-01-15 14:45 UTC, Sebas3245 commented on src/mocks/domains/reimbursementType.ts
> +const reimbursementTypeData=[
Me parece que mejor creemos este dominio en model/domains, me suena mas a parte de la aplicacion que algo configurable en el back-end, pasarlo alla con la estructura que se maneja de ese lado

2024-01-22 14:36 UTC, Sebas3245 requested changes

2024-01-22 14:36 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/index.tsx
> +  }, [initialValues]);
Creo que esta dependencia no es necesaria

2024-01-22 14:36 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
> +  const detailReimbursement = Object(optionsFormReimbursement());
Tratemos de no usar estas clases Object para encapsaular valores, esto se usa en los mappers de valores que llegan en el back-end porque al aser un servicio externo no podemos asegurar el tipo de dato que llega, pero de este lado si debeos hacer lo posible por no hacerlo porque puede generar confusiones en el tipado

2024-01-22 14:36 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
> +    transferToExternalAccount: usersMock.map((dataUser) => {
Aca habria que configurar para que solo traiga lo del user[0] esto debido a que hay estaria mapeando varios usuarios, caso que nunca se daria, revisar si esto sucede en otras partes del desarrollo ya que es importante que se apunte al usuario [0] siempre

2024-01-22 23:03 UTC, Sebas3245 requested changes

2024-01-22 23:03 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
> +      const defaultValueReimbursementType = Object(
Aca tambien se esta usando la clase Object para encapsular y convertir ese valor

2024-01-22 23:27 UTC, Sebas3245 requested changes
Esta sucediendo algo raro, si por ejemplo selecciono una cuenta interna y vuelvo al paso anterior de "Meta" (pero sin cambiar nada )y vuelvo al de Reembolso, por algun motivo se borro la seleccion que hice, esto solo deberia pasar si yo cambie algo en el paso de Meta al regresar, revisa el stepRules a veces que esta provocando esto

2024-01-23 14:04 UTC, Sebas3245 requested changes

2024-01-23 14:04 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/config/assisted.ts
>  ) => {
Aca un ajuste adicional, pasemos esta funcion de stepRules mejor a un archivo utils.ts en ProgrammedSavingFixedRequest, ya esta funcion tiene  mucha logica y no seria tanto de configuracion

2024-01-23 14:04 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/types.ts
> +interface IFormReimbursement {
Llamemos a esta interfaz "IReimbursementOptions"

2024-01-23 14:50 UTC, Sebas3245 requested changes

2024-01-23 14:50 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/utils.ts
> +        id: usersMock[0].bankTransfersAccount.description,
Validemos la existencia de estos indices

2024-01-23 14:51 UTC, Sebas3245 requested changes

2024-01-23 14:51 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/ReimbursementForm/types.ts
> +interface IFormReimbursement {
Faltaria este ajuste

2024-01-24 12:58 UTC, Sebas3245 requested changes

2024-01-26 00:54 UTC, Sebas3245 approved these changes

2024-01-26 00:54 UTC, merged