Cr/407/mock creating member in family group
selsa-inube/personas pull request #491
Opened 2024-01-16 12:43 UTC by CristianRojas-47

2024-01-16 23:51 UTC, ANGIECATHERINEP requested changes
El readOnly en los dos últimos pasos no se esta validando

2024-01-24 13:41 UTC, ANGIECATHERINEP approved these changes

2024-01-26 01:08 UTC, Sebas3245 requested changes
Hacer tambien un npm run lint para validar que warnings podemos corregir

2024-01-26 01:08 UTC, Sebas3245 commented on src/design/feedback/Assisted/styles.ts
> +  border: 3px solid
En el figma este borde aparece en varias partes de 2px, confirmar con Leonardo

2024-01-26 01:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/config/initialValues.ts
> +  identificationNumber: 0,
No deberia empezar en 0, coloquelo como tipo string para que inicialice con string vacio, ya en los inputs si lo maneja como number, como en otros ejemplos de TextField tipo number que hay en el proyecto

2024-01-26 01:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
> +    onSubmit: onSubmit || (() => {}),
Aca retornemos => true en lugar de => {} y en los otrosd formularios igual

2024-01-26 01:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/index.tsx
> +      onAddMember(
Esto tambien deberia hacerse en handleFinishedAssisted no?

2024-01-29 13:36 UTC, Sebas3245 requested changes

2024-01-29 13:36 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/ContactDataForm/index.tsx
> +    if (!readonly) {
Que pasaria si se usa de esta forma:

`if (!readonly && formik.dirty || readonly) {
  formik.validateForm().then((errors) => {
    onFormValid(Object.keys(errors).length === 0);
  });`
  
  Para no duplicar el validateForm

2024-01-29 15:13 UTC, Sebas3245 requested changes
Si lleno los datos de un nuevo miembro familiar manualmente, en la parte de informacion selecciono parentesco:

![image](https://github.com/selsa-inube/personas/assets/55991750/a80c5c1a-e4e9-4c14-ab8d-c45f16d149ec)


El boton de siguiente se habilita sin haber seleccionado "depende economicamente" que es requerido:

![image](https://github.com/selsa-inube/personas/assets/55991750/e72bb828-a2b2-46ed-a4f4-fcebac53b7e1)

2024-01-29 21:10 UTC, Sebas3245 requested changes
En el paso de verficacion de crear familiar no mostremos los input que no se diligenciaron, por ejemplo hay varios campos que no son requeridos, si yo como usuario no los diligencio no deberian aparecer en la verificacion, solo los que si llené

2024-01-29 21:43 UTC, Sebas3245 approved these changes

2024-01-29 21:43 UTC, merged