Ap/19/redirect to my credits from box
selsa-inube/personas pull request #50
Opened 2023-08-04 22:14 UTC by ANGIECATHERINEP

2023-08-05 04:54 UTC, novadeveloper14 requested changes
En index.tsx falta pasarle la prop cursorHover={true}, a el <Icon /> y a los <Text /> de title y subtitle.

2023-08-05 04:54 UTC, novadeveloper14 commented on src/components/cards/Box/index.tsx
> +        <StyledLink to={navigateTo}>
debemos remplazar el componente: ` <Stack alignItems="center" gap="s100">` por <StyledLink /> de tal manera que encierre solo el icono y los textos de title y subtitle, y en los estilos pasarle los estilos correspondientes que antes el Stack hacia.

2023-08-08 17:26 UTC, novadeveloper14 approved these changes
El requerimiento se realizo correctamente.

2023-08-08 17:50 UTC, Sebas3245 requested changes
Hay un comportamiento que esta curioso y es que para que el hover haga efecto tengo que poner el mouse encima ya sea del icon, del title o del subtitle, no estoy seguro, pero creo que al acercar el mouse a styledlink como tal debería hacer el efecto hover en los 3, sería bueno en este caso consultar con leonardo si los 3 deben hacer hover y si es así utilizar parentHover para lograr el comportamiento adecuado.

2023-08-08 21:06 UTC, Sebas3245 approved these changes

2023-08-08 21:06 UTC, merged