jg/09/create-Breadcrumbs-component-and-subcomponents
selsa-inube/personas pull request #51
Opened 2023-08-05 04:35 UTC by novadeveloper14

2023-08-08 16:51 UTC, ANGIECATHERINEP requested changes

2023-08-08 16:51 UTC, ANGIECATHERINEP commented on src/design/navigation/Breadcrumbs/index.tsx
> +
Al revisar se observa que los breadcrumbs de desktop y mobile están intercambiados, es decir el contenido del breabreadcrumbs de desktop de ser el de mobile y viceversa 
![image](https://github.com/selsa-inube/personas/assets/88405711/44ac1b44-5f61-4a1c-bf01-88b32ec8748f)

![image](https://github.com/selsa-inube/personas/assets/88405711/4fe4f0df-57b6-454c-a2c7-bf5dfc3e9d37)

2023-08-08 16:51 UTC, ANGIECATHERINEP commented on src/design/navigation/Breadcrumbs/index.tsx
> +          isActive={crumbs[0].isActive}
esta apareciendo una advertencia por consola de la prop isActive
![image](https://github.com/selsa-inube/personas/assets/88405711/aee42be4-1485-432b-8dc9-1278faa4c9d8)

2023-08-08 22:53 UTC, ANGIECATHERINEP approved these changes

2023-08-09 13:32 UTC, Sebas3245 requested changes
En general hay que refactorizar ya que el desarrollo esta implementado con reglas y estándares del proyecto design-system y eso hará que choque en lectura de codigo con los demás componentes que tenemos en este proyecto, deje unos comentarios puntuales, pero estos se deben tener en cuenta en general ya que las correcciones se ven necesarias en todo el desarrollo, recordar que debemos manejar las reglas que hemos establecido tanto para "personas" como para "linpar", por lo tanto hacer una revisión completa al desarrollo con base a los comentarios que se dejaron.

2023-08-09 13:32 UTC, Sebas3245 commented on src/design/navigation/Breadcrumbs/index.tsx
> +export interface IBreadcrumbsProps {
el export debería hacerse al final del archivo con "export type {}" igual que como se ha hecho con todas las interfaces de los componentes, verificar si hay otros casos en su desarrollo donde se esté haciendo así.

2023-08-09 13:32 UTC, Sebas3245 commented on src/design/navigation/BreadcrumbEllipsis/index.tsx
> +export interface IRoute {
Deberia estar en un types.ts

2023-08-09 13:32 UTC, Sebas3245 commented on src/design/navigation/BreadcrumbEllipsis/index.tsx
> +const BreadcrumbEllipsis = (props: IBreadcrumbEllipsisProps) => {
Declaremos el componente de manera convencional, con "function"

2023-08-09 13:32 UTC, Sebas3245 commented on src/design/navigation/BreadcrumbEllipsis/index.tsx
> +  const containerRef = useRef<HTMLDivElement | null>(null);
**(typescript tip):** En este caso no hace falta agregar que el tipo sea "| null" ya que si el valor se inicializa con (null) ya toma que recibe ambos tipos

2023-08-09 13:32 UTC, Sebas3245 commented on src/design/navigation/BreadcrumbEllipsis/stories/BreadcrumbEllipsis.stories.tsx
> +    (Story: React.ElementType) => (
Acá debe ser tipo StoryFn

2023-08-09 17:33 UTC, Sebas3245 requested changes

2023-08-09 17:33 UTC, Sebas3245 commented on src/design/navigation/BreadcrumbMenu/types.ts
> +interface IBreadcrumbRoute {
Cuál es la diferencia entre esta interfaz y IRoute??

2023-08-09 19:16 UTC, Sebas3245 approved these changes

2023-08-09 19:16 UTC, merged