feat(creditAmortization): add column type in amortization table to in…
selsa-inube/personas pull request #517
Opened 2024-01-23 21:49 UTC by ANGIECATHERINEP

…dicate the payment

2024-01-24 16:38 UTC, novadeveloper14 requested changes
hay que ajustar los Breakpoints de tal forma que el espaciado de la derecha de la tabla no se recorte:

![image](https://github.com/selsa-inube/personas/assets/87447257/4d5aceb4-4858-48d3-8355-9738ed437507)

2024-01-25 12:04 UTC, novadeveloper14 approved these changes

2024-01-25 12:38 UTC, Sebas3245 requested changes
de 658px a 710px de ancho se esta desbordando la tabla

2024-01-25 13:20 UTC, Sebas3245 approved these changes

2024-01-25 13:20 UTC, merged