jg/615/Payments-plan-sum-fixed-and-variable-interest
selsa-inube/personas pull request #519
Opened 2024-01-24 15:42 UTC by novadeveloper14

2024-01-24 16:16 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-01-24 20:05 UTC, Sebas3245 requested changes

2024-01-24 20:05 UTC, Sebas3245 commented on src/services/iclient/credits/mappers.ts
> +    (Number(payment.fixedInterestValue) || 0) +
El "|| 0" deberia estar dentro de la instancia que se crea con la clase Number, ya que la idea es no generar un NaN

2024-01-25 12:35 UTC, Sebas3245 approved these changes

2024-01-25 12:35 UTC, merged