Cr/620/change validations in cdat to on change
selsa-inube/personas pull request #572
Opened 2024-02-02 00:33 UTC by CristianRojas-47

2024-02-02 13:34 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-02-02 21:29 UTC, Sebas3245 requested changes
Esta sucediendo el siguiente caso:
En el paso 1 coloco 1400000
Paso al siguiente y coloco pago de intereses unicos y al hacer unicametne click en el campo plazo en numero de dias, sale esto:

![image](https://github.com/selsa-inube/personas/assets/55991750/4a23b510-207f-466d-95df-91e3da7369f9)

2024-02-05 19:01 UTC, Sebas3245 requested changes
![image](https://github.com/selsa-inube/personas/assets/55991750/aabb4703-0b55-4009-891a-535405c5f4b1)
Replicando el mismo caso que el mencionado en la revision anterior pasa que antes de darle **simular** ya se habilita el boton de siguiente

2024-02-06 12:45 UTC, Sebas3245 approved these changes

2024-02-06 12:45 UTC, merged