Ap/690/add fieldsets in informacion personal step
selsa-inube/personas pull request #577
Opened 2024-02-05 16:08 UTC by ANGIECATHERINEP

2024-02-05 20:25 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-02-06 12:44 UTC, Sebas3245 requested changes
![image](https://github.com/selsa-inube/personas/assets/55991750/21d99f12-1734-4af1-a0b4-824ecc2dfb6f)
No aparece el tipo de identificación

2024-02-06 12:44 UTC, Sebas3245 commented on src/mocks/users/referenceUsersMocks.ts
> +      country: "Colombia",
Usemos codigos de dominio no valores, si el dominio no existe habria que crealo en mocks/domains

2024-02-06 12:44 UTC, Sebas3245 commented on src/mocks/users/users.mocks.tsx
> +        city: "Bogota",
Hay que seguir usando los codigos de dominio, no el valor como tal

2024-02-06 19:37 UTC, Sebas3245 requested changes
![image](https://github.com/selsa-inube/personas/assets/55991750/dcca3450-b55c-476b-a254-9b799eebd533)
Hay que usar el domain valueOf para traer el valor del codigo de dominio y que no se vean los codigos ahi en los campos, si no existen los dominios de pasises y departamentos hay que crearlos en mocks/domains

2024-02-06 20:00 UTC, Sebas3245 requested changes
En la verificacion siguen apareciendo los codigos:

![image](https://github.com/selsa-inube/personas/assets/55991750/3119d4a1-931a-4878-8181-add750e93505)

Ahi tambien toca usar el domain valueOf

2024-02-06 20:34 UTC, Sebas3245 approved these changes

2024-02-06 20:34 UTC, merged