jg/520/Mock-debito-atomatico-in-cuota-step-Ah-programado
selsa-inube/personas pull request #580
Opened 2024-02-06 12:41 UTC by novadeveloper14

2024-02-09 14:02 UTC, ANGIECATHERINEP requested changes
Al seleccionar en el campo día de pago se habilita el botón siguiente si aun  haber seleccionado los campos entidad bancaria y numero de cuenta
![image](https://github.com/selsa-inube/personas/assets/88405711/4dbc26a3-ab93-48af-94d4-d71db4c10319)

2024-02-20 13:06 UTC, ANGIECATHERINEP approved these changes

2024-02-21 19:31 UTC, Sebas3245 requested changes
![image](https://github.com/selsa-inube/personas/assets/55991750/ec01483f-8871-463e-82bb-a4a61b4d6782)
Aca las opciones deberian ser:
Día 1 del mes
Día 15 del mes
Día 30 del mes
Estos valores aplican para la peridiocidad quincenal, semestral y anual

2024-02-22 12:47 UTC, Sebas3245 requested changes
Algo que no pasa en main pero esta pasando con los ajustes de este desarrollo es que al seleccionar canales fisicos de recaudo como medio de pago y avanzar hasta asignar la peridiocidad sin seleccionar dia de pago se esta habilitando el boton de siguiente lo cual no deberia pasar:

![image](https://github.com/selsa-inube/personas/assets/55991750/ec2f3f4c-5470-494a-94f8-c9e8e5d80276)


Y aparte falta lo de este comentario:
![image](https://github.com/selsa-inube/personas/assets/55991750/6b9ed5fd-27c2-4c0e-b2fe-9c86b2d9d4c6)

2024-02-22 20:21 UTC, Sebas3245 requested changes

2024-02-26 12:37 UTC, Sebas3245 approved these changes

2024-02-26 12:37 UTC, Sebas3245 commented on src/utils/forms/forms.tsx
> +              placeholder={field.placeholder || undefined}
No usar este || undefined

Simplemente en IFormField poner el placeholder como opcional y si por ejemplo en el Textfield es requerido poner un || ""

2024-02-26 12:37 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
> +  if (formik.values.accountToDebit === "externalOwnAccountDebit") {
Aca no aplica esta condicional, se debe poner accountToDebit como dsicriminante en el return al igual que paymenyMethod y dentro de sus propiedades irian sus posibles opciones como "externalOwnAccountDebit" para asi definir que campos mostrar

2024-02-26 12:37 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
> +        ? " "
Aca dejar un string sin espacios

2024-02-26 12:37 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/index.tsx
> +  const customHandleAccount = (event: React.ChangeEvent<HTMLSelectElement>) => {
No enviemos esta funcion al structureQuotaForm simplemente añadir si el name es igual al name del campo que contiene el account en la funcion customHandleChange y asi dentro de esa condicion llamar a customHandleAccount con eso no añadimos funciones en el IFormField es decir ese "onChange" que ´puso ya que este ya recibe la funcion personalizada por defecto y por ejemplo structureQuotaForm o la que sea de otro formulario se podria llenar de recibir funciones de onChange individuales y esa no es la idea, por eso es mejor centralzair todo en un customHandleChange y ya si esta por dentro llama a otras funciones ya es un desacople que se puede hacer

2024-02-28 23:02 UTC, Sebas3245 requested changes
![image](https://github.com/selsa-inube/personas/assets/55991750/1f87935e-cfa0-429c-a7e5-492e8b08f9f7)
El numero de cuenta deberia aparecer aun antes de seleccionar la cuenta a debitar, solo que deberia aparecer disable, figma:

![image](https://github.com/selsa-inube/personas/assets/55991750/c0aa0dd1-d8bf-4eaf-b954-fe403d3559b5)

2024-03-04 13:42 UTC, Sebas3245 requested changes

2024-03-04 13:42 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
> +        ...(formik.values.accountToDebit === "externalOwnAccountDebit"
Si bien esto ya funciona y me parece bien, podriamos hacer que el codigo sea mas diciente con el objetivo, validar que si la cuenta a debitar es internalOwnAccountDebit entonces aparece el field y todos los demas entonces serian [], es decir hacer la validacion al reves porque si no estariamos diciendo en el codigo que el objetivo principal seria retonar el arreglo vacio cuando es alreves

2024-03-04 14:41 UTC, Sebas3245 requested changes

2024-03-04 15:39 UTC, novadeveloper14 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
> +        ...(formik.values.accountToDebit !== "externalOwnAccountDebit"
se realizo la validación como se requiere pero se le agrego "OR !formik.values.accountToDebit" para que inicialmente el campo se muestre con el readonly, ya que si se hace solo la validación formik.values.accountToDebit === "internalOwnAccountDebit" quedaría con el mismo funcionamiento como cuando se agrego la propiedad internalOwnAccountDebit a accountToDebit el accountNumberSelect no se estaría mostrando

2024-03-04 17:34 UTC, Sebas3245 commented on src/pages/request/savings/ProgrammedSavingFixedRequest/forms/QuotaForm/config/form.ts
> +        ...(formik.values.accountToDebit !== "externalOwnAccountDebit"
Mmm, no realmente lo del ultimo comentario eera mas una pregunta que hacer el ajuste, en ese caso creo que se ve feo el OR, dejelo nuevamente con "formik.values.accountToDebit !== "externalOwnAccountDebit""

2024-03-04 20:12 UTC, Sebas3245 approved these changes

2024-03-04 20:12 UTC, merged