Cr/674/use endpoint to fetch ahorros permanentes products
selsa-inube/personas pull request #582
Opened 2024-02-06 19:59 UTC by CristianRojas-47

2024-02-07 17:15 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-02-07 18:06 UTC, Sebas3245 requested changes

2024-02-07 18:06 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
>    const movements = Array.isArray(savings.lastMovementTheSavingProducts)
Pasemos esto a otra funcion llamada mapSavingProductMovementsApiToEntities y que esa llame una mapSavingProductMovementsApiToEntity, dentro del mismo archivo de mappers de getSavings

2024-02-07 18:06 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
> +    Object(savings.accumulatedSavingProducts)[0]?.creditMovementPesos || 0;
Hay que asegurar la existencia de ese indice 0

2024-02-07 18:06 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
>    let productType: ProductType = String() as ProductType;
Quitemos estos String as ProductType, no se que proposito cumplen pero si es un string vacio pues hay que asignarlo como tal ""

2024-02-07 18:06 UTC, Sebas3245 commented on src/pages/admin/home/index.tsx
> +          saving.type === permanentSavingsCode ||
Ajustemos estos "Code" para que tengan los valores que llegan en el back-end por ejemplo "PERMANENTSAVINGS"

2024-02-07 18:06 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
> +  if (savings.productCatalogCode === "1" && permanentSavings) {
No validemos nada con ese productCatalogCode, no debemos usarlo

2024-02-07 18:06 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
> +    title = "Aportes sociales";
Creemos una funcion aca en mappers que reciba el tipo de product y el numero de producto que retorne un objeto que dependiendo del tipo de producto arme una estructura title, descriptiob, productType, esto con el fin de no crear condicionales por cada tipo de producto, en lo posible eso debe evitarnos tambien el uso de esas constantes permanentSavings y contributions

2024-02-08 14:14 UTC, Sebas3245 requested changes

2024-02-08 14:14 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
> +        savings.type === "PERMANENTSAVINGS" || savings.type === "CONTRIBUTIONS",
Aca deberiamos comparar con los codigos como "permanentSavingsCode "

2024-02-08 14:14 UTC, Sebas3245 commented on src/services/iclient/savings/getSavings/mappers.ts
> +  const { title, description, productTypeValue } = getProductDetails(
Hagamos lo siguiente para esta funcion, que el objeto que retorne solo tenga title y description, con eso arriba le podemos a la constante productType que sea de tipo ProductType: 

const productType: ProductType = Object(savings.productType).code;

Con eso ya no tendriamos que hacer abajo el "as" en el type si no que solo le pasamos "producType"

2024-02-08 14:44 UTC, Sebas3245 approved these changes

2024-02-08 14:44 UTC, merged