fix(updateDat): add descriptions in Adicionar familiar modal assisted
selsa-inube/personas pull request #593
Opened 2024-02-09 15:38 UTC by ANGIECATHERINEP

2024-02-09 19:58 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-02-09 20:01 UTC, Sebas3245 requested changes

2024-02-09 20:01 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
> -    if (formik.dirty) {
Porque eliminaste esta condicion? lo que pasa es que al no tenerla si yo hago click en el campo de identificacion empieza con error

2024-02-09 20:04 UTC, ANGIECATHERINEP commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/IdentificationDataForm/index.tsx
> -    if (formik.dirty) {
Lo que pasa es que si se deja, el botón de siguiente se habilita sin haber ingresado el numero de identificación y deja pasar al los otros pasos 
![image](https://github.com/selsa-inube/personas/assets/88405711/6a296e8e-8c80-43d7-8069-6013d9e8b7e5)

2024-02-12 14:56 UTC, Sebas3245 approved these changes

2024-02-12 14:56 UTC, merged