Cr/699/adjust editar familiar modal
selsa-inube/personas pull request #607
Opened 2024-02-13 23:31 UTC by CristianRojas-47

2024-02-14 14:55 UTC, novadeveloper14 approved these changes

2024-02-14 21:42 UTC, Sebas3245 requested changes
Si cambio algo y vuelvo a ponerlo como estaba, sigue saliendo el boton de guardar y no deberia

2024-02-14 21:42 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
> +                  formik.values.isDependent === "Y"
No usemos valores quemados, usemos el dominio para comparar

2024-02-15 12:41 UTC, Sebas3245 requested changes
Aun falta resolver este comentario:
![image](https://github.com/selsa-inube/personas/assets/55991750/4b4036f1-5c06-41e4-b5bd-4b2d2d6f7b8f)

2024-02-15 19:08 UTC, Sebas3245 requested changes

2024-02-15 19:08 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/forms/InformationDataForm/types.ts
> +  isDependent?: string;
Busquemos la forma de solucionar el problema dejando esta propeidad como un booleano, esto debido a que para nosotros estos campos son indicadores de verdadero o falso, ya el hecho de tener un Y o N es algo que le interesa al back-end pero para nosotros una Y o N nunca nos sera totalmente claro sobre cual es el valor que necesitamos para validarlo

2024-02-21 13:54 UTC, CristianRojas-47 reviewed
Revisando el proyecto y teniendo en cuenta que el único dato que estamos manejando como booleano, llego a esta conclusión:

Cambiar ese dato a string sería fácil y no afectaría la estructura de los componentes Select, Textfield, DropdownMenu y DropdownItem. Pero si optamos por usar booleanos en esos componentes, podríamos tener problemas en otras partes de la aplicación.

Además, pensando en futuras actualizaciones, usar strings sería más flexible y nos ayudaría a incorporar nuevas funciones o requisitos sin complicaciones, mientras que integrar booleanos podría resultar en rigidez en esta etapa.

2024-02-21 21:21 UTC, Sebas3245 requested changes

2024-02-21 21:21 UTC, Sebas3245 commented on src/components/modals/forms/update-data/FamilyGroupModals/FamilyMemberViewModal/index.tsx
> +                value={formik.values.isDependent || ""}
Aca es necesario el || ""? lo digo porque parece que en los valores iniciales esta quedando en "N" entonces ya se esta asegurando que se inicia con un valor

2024-02-21 21:39 UTC, Sebas3245 requested changes
Si edito este segundo registro:
![image](https://github.com/selsa-inube/personas/assets/55991750/927abaf1-9f12-4c30-b728-cf495ee28a25)

Y le pongo que si depende economicamente y vuelvo a darle editar no aparece lo que edite anteriormente

2024-02-21 22:55 UTC, Sebas3245 approved these changes

2024-02-21 22:55 UTC, merged