jg/723/fetch-and-render-savings-commitments
selsa-inube/personas pull request #608
Opened 2024-02-14 12:36 UTC by novadeveloper14

2024-02-14 13:18 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-02-14 13:51 UTC, Sebas3245 requested changes
Agreguemos el modal de proximo pago como esta por ejemplo en creditos y aparte la tabla de pagos recientes que vendria a ser la propiedad lastMovementTheSavingPlans del json del back

![image](https://github.com/selsa-inube/personas/assets/55991750/d403e746-ebf5-4813-8b97-2c167f4f686d)

2024-02-14 13:51 UTC, Sebas3245 commented on src/App.tsx
> +          <CommitmentsProvider>
No es necesario crear otro contexto, los compromisos deberian ser un estado dentro del contexto global de savings

2024-02-14 13:51 UTC, Sebas3245 commented on src/services/iclient/savings/getCommitments/mappers.ts
> +  let inArrears;
Deberia ser dese el inicio un booleano el false

2024-02-14 13:51 UTC, Sebas3245 commented on src/services/iclient/savings/getCommitments/mappers.ts
> +    type: "PROGRAMMEDSAVINGS",
Aca este tipo no puede ir ese ya que hay que obtener el tipo del registro que llega del back-end

2024-02-14 13:51 UTC, Sebas3245 commented on src/services/iclient/savings/getCommitments/mappers.ts
> +    type: "PROGRAMMEDSAVINGS",
En caso de que sea necesario habria que crear un enum para los types de compromisos asi como se hizo con los productos de ahorro

2024-02-14 13:51 UTC, Sebas3245 commented on src/services/iclient/savings/getCommitments/mappers.ts
> +  let attributes;
Mejor iniciela como una constante con un arreglo vacio y abajo solo hareia push, con eso no hay que hacer el || [] al final y el codigo queda legible desde el inicio

2024-02-15 12:40 UTC, Sebas3245 requested changes

2024-02-15 12:40 UTC, Sebas3245 commented on src/context/savings/index.tsx
> +    commitments: [],
Hay que crea el estado aparte para los commitmets, no dentro del savings, es decir en el mismo context pero en otro estado.

2024-02-15 12:40 UTC, Sebas3245 commented on src/model/entity/product.ts
> +  OS = "0S",
Este tipo de compromiso y el de abajo no deberian estar porque ya no existirian esos codigos

2024-02-15 12:40 UTC, Sebas3245 commented on src/pages/admin/savings/SavingsCommitments/interface.tsx
> +import { NextPaymentModal } from "@components/modals/credit/NextPaymentModal";
Mueva el NextPaymentModal a components/modals, para que quede mas general y no especifico para credits

2024-02-15 13:32 UTC, Sebas3245 approved these changes

2024-02-15 13:32 UTC, merged