Ap/696/create datefield component
selsa-inube/personas pull request #616
Opened 2024-02-17 00:11 UTC by ANGIECATHERINEP

2024-02-19 15:30 UTC, CristianRojas-47 approved these changes
El requerimiento se realizo correctamente.

2024-02-19 19:58 UTC, Sebas3245 requested changes

2024-02-19 19:58 UTC, Sebas3245 commented on src/design/input/DateField/props.ts
> +    description: "Corresponds to the identifier of the textfield",
Aca se esta haciendo referencia al textfield

2024-02-19 19:58 UTC, Sebas3245 commented on src/design/input/DateField/styles.ts
> +  /*
Este comentario se puede eliminar?

2024-02-19 19:58 UTC, Sebas3245 commented on src/design/input/DateField/types.ts
> +interface ITextFieldMessage {
Aca se esta haciendo referencia al TextField en lugar del DateField

2024-02-20 14:40 UTC, Sebas3245 approved these changes

2024-02-20 14:41 UTC, merged