Ap/729/extend modal ciiu to current activity
selsa-inube/personas pull request #621
Opened 2024-02-19 22:00 UTC by ANGIECATHERINEP

2024-02-19 23:19 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-02-20 17:07 UTC, Sebas3245 requested changes
Aun falta cumplir el objetivo de la tarea que consiste en que si por ejemplo yo selecciono una actividad CIIU y luego abro nuevamente el modal para seleccionar otra, aparezca la que seleccione anteriormente, figma:

![image](https://github.com/selsa-inube/personas/assets/55991750/1d2f886b-35d2-43ab-a7be-5e3f21ad839a)

2024-02-21 13:02 UTC, Sebas3245 requested changes
Antes de realizar los cambios sugeridos, una pregunta, que pasaria si en lugar de crear un estado, al modal le pasamos por ejemplo formik.mainCiiuActivity en su propiedad selectedActivityId, con esto podriamos evitar crear dos estados en el form?

2024-02-21 13:47 UTC, ANGIECATHERINEP commented on src/components/modals/forms/update-data/EconomicActivityModal/index.tsx
> +        {selectedActivityId.length > 0 &&
Tienes razón, elimine los estados y mejor le pase al modal formik.mainCiiuActivity en su propiedad selectedActivityId

2024-02-21 13:51 UTC, Sebas3245 approved these changes

2024-02-21 13:51 UTC, merged