refactor(savings): adjust gmf attribute in view savings
selsa-inube/personas pull request #633
Opened 2024-02-22 16:07 UTC by CristianRojas-47

2024-02-22 16:16 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-02-22 20:10 UTC, Sebas3245 requested changes

2024-02-22 20:10 UTC, Sebas3245 commented on src/mocks/products/savings/utils.mocks.ts
> +  AllTransactionsAreTaxed: "Todas las transacciones",
Coloquemos los valores que faltan:

[
    {
        "code": "TotallyExcempt",
        "description": "Identifies that the mode is totally exempt"
    },
    {
        "code": "ExcemptUntilMaximum",
        "description": "Identifies that you are Exempt up to the maximum."
    },
    {
        "code": "ExcemptUntilMaximumOnPensionAllowance",
        "description": "Identifies that you are Exempt up to the maximum pension amount"
    },
    {
        "code": "AllTransactionsAreTaxed",
        "description": "Identifies that all transactions are encumbered"
    }
]

2024-02-23 01:03 UTC, Sebas3245 approved these changes

2024-02-23 01:03 UTC, merged