fix(savingsMovements): adjust movements according to type
selsa-inube/personas pull request #638
Opened 2024-02-23 19:50 UTC by CristianRojas-47

2024-02-23 20:33 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-02-26 12:39 UTC, Sebas3245 requested changes

2024-02-26 14:49 UTC, Sebas3245 requested changes

2024-02-26 18:26 UTC, Sebas3245 approved these changes

2024-02-26 18:26 UTC, merged