feat(updateDataUnassisted): add content of tab activos personales
selsa-inube/personas pull request #658
Opened 2024-02-29 15:03 UTC by ANGIECATHERINEP

2024-03-01 19:02 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2024-03-01 20:02 UTC, Sebas3245 requested changes

2024-03-01 20:02 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalAssetsForm/interface.tsx
> +  const validateButtonActivation = formik.values.entries.length === 0;
Aca ajustemos eliminando esta constante segun lo charlado

2024-03-04 14:42 UTC, Sebas3245 approved these changes

2024-03-04 14:42 UTC, merged