Ap/625/add contact data tab
selsa-inube/personas pull request #660
Opened 2024-02-29 23:33 UTC by ANGIECATHERINEP

2024-03-01 13:07 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-03-01 20:24 UTC, Sebas3245 requested changes

2024-03-01 20:24 UTC, Sebas3245 commented on src/validations/validationRules.ts
> +    .min(1000000000, validationMessages.minNumbers(10))
Aca hay que buscar la longitud correcta porque la idea es que no permita un numero menor ni mayor a 10

2024-03-01 20:24 UTC, Sebas3245 commented on src/shared/forms/ContactChannelsForm/mappers.ts
> +    landlinePhone: contactChannelsData.landlinePhone || 0,
Busquemos la manera de evitar el 0 en todas las partes del desarrollo, aplicando la solucion que encontramos en la reunion

2024-03-01 21:30 UTC, ANGIECATHERINEP commented on src/validations/validationRules.ts
> +    .min(1000000000, validationMessages.minNumbers(10))
Lo coloque de esta manera debido a que al utilizar en  Yup.number  el min o max, el toma en su primer argumento la longitud de lo caracteres, es decir que si le coloco en min y max (en el primer argumento) el 10 Yup aceptaría que solo se deba ingresar el numero 10.

en donde se tiene en cuenta la cantidad de caracteres que sean 10 es en el segundo argumento de min y max (validationMessages.minNumbers(10))

2024-03-04 13:33 UTC, Sebas3245 requested changes

2024-03-04 13:33 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/FamilyGroupForm/CreateFamilyMember/utils.ts
> +              cellPhone: 0,
Esta propiedad cellPhone parece que es opcional, podriamos no ponerla aca  para no ponerle el 0? o que en su type sea || "" para pasarle aca el "" string vacio, esto para evitar en lo posible setear esos 0

2024-03-04 13:33 UTC, Sebas3245 commented on src/validations/validationRules.ts
> +    .min(1000000000, validationMessages.minNumbers(10))
Lo que pasa es que ese validacionMessage es solo un string que aparecera con base a la regla del min por ejemplo, por ende no nos serviria hacerlo de esta forma porque si bien el mensaje puede ser el esperado, la regla no es la que aplica, buscando en la documentacion de  yup no hay alguna regla/metodo de ellos que sea como el min pero para controlar la longitud en lugar del valor?

2024-03-05 16:30 UTC, Sebas3245 approved these changes

2024-03-05 16:30 UTC, merged