Cr/631/add referencias personales tab
selsa-inube/personas pull request #664
Opened 2024-03-01 16:21 UTC by CristianRojas-47

2024-03-01 17:17 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-03-01 18:36 UTC, Sebas3245 requested changes

2024-03-01 18:36 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
> +  const validateButtonActivation = formik.values.entries.length === 0;
Esta validacion la podriamos dejar directamente sobre donde se esta llamando para no crear una constante que nos actualice el estado

2024-03-01 20:05 UTC, Sebas3245 requested changes

2024-03-01 20:05 UTC, Sebas3245 commented on src/pages/general/UpdateData/forms/PersonalReferencesForm/interface.tsx
> +                loading || !formik.dirty || formik.values.entries.length === 0
No creo que esta validacion nos sirva porque eso es teniendo en cuenta que siempre van a ser 0 los registros y si por ejemplo logramos consultarlos mas adelante van a llegar varios, la validacion correcta seria el formik.values.entries.length !== form.initialValues.entries.length

2024-03-04 14:14 UTC, Sebas3245 approved these changes

2024-03-04 14:14 UTC, merged