jg/69/extend-Button-to-return-Link
selsa-inube/personas pull request #67
Opened 2023-08-11 15:41 UTC by novadeveloper14

2023-08-11 16:17 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2023-08-11 16:37 UTC, Sebas3245 requested changes

2023-08-11 16:37 UTC, Sebas3245 commented on src/design/input/Button/index.tsx
> +  function renderButtonContent() {
Estas funciones que retornan jsx debemos dejarlos fuera del componente y recibir los parámetros (NO DESESTRUCTURANDO DE PROPS)

2023-08-11 16:37 UTC, Sebas3245 commented on src/design/input/Button/Button.stories.tsx
> +WithLink.args = {
Dejemos solo la historia default y theme, esto porque con los controls en el default el usuario puede asignar el type link y el path, tambien tengamos esto presente de ahora en adelante en todos los desarrollos en la medida de lo posible.

2023-08-11 16:37 UTC, Sebas3245 commented on src/design/input/Button/styles.ts
> +const StyledLink = styled(Link)<IStyledLink>`
Todo este css creo que es igual al StyledButton, busque una forma de generalizar de tal forma que StyledLink y StyledButton hereden el mismo css si es posible, ya que si o si hay que manejar <button /> y <Link /> aparte, pero por mantenibilidad sería bueno buscar un solo punto de estilos

2023-08-11 23:44 UTC, Sebas3245 requested changes
Realizar ajustes y solucionar conflictos

2023-08-11 23:44 UTC, Sebas3245 commented on src/design/input/Button/index.tsx
> +  iconBefore: React.JSX.Element | undefined,
Recuerde que decir "| undefined" es lo mismo que poner una prop o parametro con "parametro?: tipo" y por estandar de nosotros debemos manejar el "?"

2023-08-11 23:44 UTC, Sebas3245 commented on src/design/input/Button/Button.stories.tsx
>  };
Coloquemosle un type por defecto aca en el default

2023-08-14 14:07 UTC, Sebas3245 approved these changes
Excelente 👍

2023-08-14 14:07 UTC, merged