Ap/803/mock cupo credito data
selsa-inube/personas pull request #680
Opened 2024-03-07 17:15 UTC by ANGIECATHERINEP

2024-03-07 19:10 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-03-08 13:52 UTC, Sebas3245 requested changes
Aun falta agregar los datos para este detalle:
![image](https://github.com/selsa-inube/personas/assets/55991750/5225fbf2-3ae4-423d-8d31-efec7d61e947)
Se podria hacer agregando una propiedad details dentro de ICreditQuota con la estructura respectiva con cada propiedad que aparece en la imagen

2024-03-08 13:52 UTC, Sebas3245 commented on src/mocks/products/cards/creditQuotas.mock.ts
> +const creditQuotasMock: IProduct[] = [
Creemos una interfaz ICreditQuota para poder tener todo lo relacionado a un cupo de credito aparte de IProduct y asi no crear esa propiedad adicional en IProduct, en esa nueva interfaz podemos omitir crear el type, amortization y commitments

2024-03-08 13:52 UTC, Sebas3245 commented on src/mocks/products/cards/creditQuotas.mock.ts
> +        attributes: [
Estos atributos en teoria deberian estar arriba en el objeto principal en su propiedad atributos, mas no aca separados ya que son un mismo cupo de credito y se van a acceder desde el mismo punto

2024-03-08 13:52 UTC, Sebas3245 commented on src/mocks/products/cards/creditQuotas.mock.ts
> +                id: "consumption_date",
En la interfaz de consumos coloquemos estos valores como propiedades para no colocarlos como atributos

2024-03-08 13:54 UTC, Sebas3245 requested changes

2024-03-08 13:54 UTC, Sebas3245 commented on src/mocks/products/cards/creditQuotas.mock.ts
> +                label: "pago minimo interés corriente",
Coloquemos todos estos label con la primer letra en mayuscula, revisar en que otras partes del desarrollo aplicaria hacer el ajuste

2024-03-11 12:49 UTC, merged