Cr/801/create consulta de tarjetas page
selsa-inube/personas pull request #682
Opened 2024-03-12 23:46 UTC by CristianRojas-47

2024-03-13 00:13 UTC, ANGIECATHERINEP approved these changes
El requerimiento se realizo correctamente

2024-03-13 12:58 UTC, Sebas3245 requested changes

2024-03-13 12:58 UTC, Sebas3245 commented on src/pages/admin/cards/Card/index.tsx
> +    if (cards.length > 0) {
La logica que tenemos en este useEffect y en el otro guardemoslas en unas funciones aparte y las llamamos dentro de estos useEffect, esto porque ya son bastantes lineas y seria bueno darles un nombre a los procesos que se estan haciendo dentro de unas funciones

2024-03-13 12:58 UTC, Sebas3245 commented on src/pages/admin/cards/Card/index.tsx
> +  }, [user, accessToken, cards, setCards]);
Quitemos los setState como dependencias en los useEffect ya que no serian tan necesarios y si estarian creando otro renderizado

2024-03-14 00:42 UTC, Sebas3245 approved these changes

2024-03-14 00:42 UTC, merged