jg/804/Mock-cupo-de-credito-Box-in-consulta-de-tarjetas
selsa-inube/personas pull request #686
Opened 2024-03-14 19:41 UTC by novadeveloper14

2024-03-15 01:13 UTC, ANGIECATHERINEP requested changes
en últimos movimientos algunos iconos no se ven bien en mobile
![image](https://github.com/selsa-inube/personas/assets/88405711/1b618061-928b-4709-a5d0-e638e3c679ff)

y hay que solucionar conflictos

2024-03-15 14:51 UTC, ANGIECATHERINEP approved these changes

2024-03-15 19:30 UTC, Sebas3245 requested changes
Resolver conflictos, aparte es importante no eliminar la data de los mocks de cupo ya existen ya que se estan usando actualmente

2024-03-15 19:30 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/modals.ts
> +const infoModalData: IInfoModalProps = {
Aca hay un error de la semantica que manejamos en el nombre de esa interfaz.

2024-03-15 19:30 UTC, Sebas3245 commented on src/utils/dates.ts
> +  timeString = `${hour}:${minute} ${period === "p." ? "pm" : "am"}`;
Para validar si es am o pm es mejor que lo haga consultando las horas del objeto date y validando si es mayor o igual a 12, con eso se ahorra crear un timeFormatter, aunque realmente no es un formateador si no que ya esta formateado, hay que corregir esa semantica en la declaracion de variables

2024-03-15 19:30 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/modals.ts
> +  portalId: "modals",
El portal id no seria siempre el mismo? para que lo hariamos dinamico en un objeto?

2024-03-15 19:30 UTC, Sebas3245 commented on src/model/entity/product.ts
> +  quotasMovementsType?: EQuotasMovementType;
Solo ponerle de nombre type ya serviria, esto para no alejarnos del enfoque de que esta interfaz es para movimientos en general, aparte la palabra movement sobraria ya que el nombre de la interfaz ya hace referencia a un movimiento, recomiendo tener presente estos puntos para mejorar la semantica de los nombres de propiedades o variables

2024-03-18 14:56 UTC, Sebas3245 requested changes

2024-03-18 14:56 UTC, Sebas3245 commented on src/utils/dates.ts
> +const formatPrimaryDateWithTime = (date: Date) => {
Mejor coloquemosle a la funcion formatPrimaryDate un indicador withTime?: boolean, asi opcional y con eso decidir si mostrar el time o no para no crear otra funcion tan similar

2024-03-18 16:52 UTC, Sebas3245 approved these changes

2024-03-18 16:52 UTC, merged