Ap/807/create current consumption card
selsa-inube/personas pull request #690
Opened 2024-03-18 21:00 UTC by ANGIECATHERINEP

2024-03-18 22:03 UTC, CristianRojas-47 approved these changes
El desarrollo del requerimiento es correcto.

2024-03-18 22:33 UTC, Sebas3245 requested changes

2024-03-18 22:33 UTC, Sebas3245 commented on src/pages/admin/cards/CreditQuota/index.tsx
> +    consumptionsMocks.map((consumption) => {
Usemos el context de consumptions que ya existe en creditsContext esto para no tener que eliminar estos llamados a Mocks cuando integremos esta parte, en si hay que setearle a ese estado global este objeto Mock

2024-03-18 22:33 UTC, Sebas3245 commented on src/components/cards/CurrentConsumption/index.tsx
> +            <CurrenteConsumptionBox
Creo que sobra una "e" en el nombre de este componente porque dice "Currente"

2024-03-19 21:20 UTC, Sebas3245 requested changes

2024-03-19 21:20 UTC, Sebas3245 commented on src/pages/admin/cards/CreditQuota/index.tsx
> +    consumptionsMocks.map((consumption) => {
Aun falta resolver este comentario

2024-03-19 22:23 UTC, Sebas3245 approved these changes

2024-03-19 22:23 UTC, merged