feat(select): create select component
selsa-inube/personas pull request #71
Opened 2023-08-11 23:03 UTC by CristianRojas-47

2023-08-14 21:59 UTC, novadeveloper14 requested changes

2023-08-14 21:59 UTC, novadeveloper14 commented on src/design/input/Label/index.tsx
en los design se presenta una separacion la cual no se esta viendo reflejada:

figma:

![image](https://github.com/selsa-inube/personas/assets/87447257/46cdc7f2-4f01-43c6-b147-d22813daea41)

storybook:

![image](https://github.com/selsa-inube/personas/assets/87447257/b1dd65c0-8711-4556-9a76-5f2fe95edc85)

2023-08-16 21:43 UTC, novadeveloper14 approved these changes
El desarrollo cumple con el requerimiento.

2023-08-17 00:40 UTC, Sebas3245 requested changes

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Label/index.tsx
> +export interface LabelProps {
Esta interfaz se debe exportar al final del archivo con export type

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/interface.tsx
> +function SelectUI(props: ISelectInterface, ref: React.Ref<HTMLDivElement>) {
porque el ref no pasa dentro de las props?

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/types.ts
> +interface ISelectInterface extends SelectProps {
Busquemos otro nombre para esta interface que no tenga el sufijo "interface", algo mas acorde como ISelectAttributes

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/types.ts
> +interface ISelectOptions {
Hay que tener en cuenta algo y es que una interface debe declararse en singular ya que asi nombreinterfaz[] seria la declaracion en plura, revisar esto en el resto de interfaces

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/TextField/index.tsx
> +  inputSize?: InputSize;
Tanto para este componente como para otros, no es necesario  ahcer referencia de "inputSize", con el solo "size" ya se estaria contextualizando correctamente ya que se esta asignando sobre un <TextField />

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/interface.tsx
> +    if (typeof props.handleChange === "function") {
No hace falta apuntar a handleChange desde props si ya se desestructuro, es decir se puede simplemente hacer referencia solo a "handleChange"

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/interface.tsx
> +  const handleChangeP = (event: React.ChangeEvent<HTMLInputElement>) => {
Porque tiene una "P"? revisar este y otras funciones que puedan estar igual

2023-08-17 00:40 UTC, Sebas3245 commented on src/design/input/Select/interface.tsx
> +import { IMessage } from "../TextField/types";
Esta interfaz seria bueno separarla y crear una propia por cada componente "ISelectMessage" y "ITextFieldMessage"

2023-08-17 20:12 UTC, Sebas3245 approved these changes

2023-08-17 20:12 UTC, merged