fix(cards): check first word in cupo movements to decide if we must o…
selsa-inube/personas pull request #712
Opened 2024-03-26 15:44 UTC by ANGIECATHERINEP

…r not add a prefix

2024-03-26 16:52 UTC, novadeveloper14 approved these changes

2024-04-01 14:42 UTC, Sebas3245 requested changes

2024-04-01 14:42 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +    return word === "Compra" || word === "compra" ? "" : "Compra";
Hagamos la validacion de otra manera, convirtamos la palabra de entrada en miniscula con eso no tenemos que validar ambos casos por palabra y aparte hagamos la validacion con las palabras compra, reverso y pago, para que en ningun caso suceda la redundancia, unifiquemos eso en una sola funcion en la cual se valide la primer palabra comparando estas 3 para asi saber si retornar el string de la descripcion tal cual o añadirle el prefijo, hagamos esto solo en una funcion, en la llamada getMovementDescriptionType

2024-04-01 19:23 UTC, Sebas3245 requested changes

2024-04-01 19:23 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +function prefix(type: EMovementType, description: string) {
Hagamos esto y lo de la otra funcion en una sola funcion, si te das cuenta estas condicionales perfectamente pueden ser el case que esta en getMovementDescriptionType

2024-04-01 19:51 UTC, Sebas3245 requested changes

2024-04-01 19:51 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +      return word !== "compra" ? "Compra" : "";
Pensando un poco en esta validacion seria mejor que en lugar de obtener la primer palabra, validaramos si el texto completo incluye estas palabras con el .includes, esto porque igual puede sonar redundante si la palabra esta de terceras y asi, con eso ya sabemos en cualquier caso si ponemos ese prefijo o no

2024-04-01 20:15 UTC, Sebas3245 requested changes

2024-04-01 20:15 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +  const text = description && description.toLowerCase().split(" ");
Con el ultimo ajuste ya no seria necesario hacer un split, hasta el toLowerCase quedaria listo apra que podamos validar

2024-04-01 20:15 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +  type?: EMovementType,
Estos parametros no deberian ser opcionales, en si son necesarios para realizar la logica de la funcion

2024-04-01 20:15 UTC, Sebas3245 commented on src/pages/admin/cards/Card/config/product.ts
> +  type?: EMovementType,
Con eso podemos omitir las validaciones que estan abajo de la existencia de las mismas

2024-04-01 21:41 UTC, Sebas3245 approved these changes

2024-04-01 21:41 UTC, merged