fix: remove section of Solicitar wit all its links from nav and Fulls…
selsa-inube/personas pull request #714
Opened 2024-03-27 20:11 UTC by ANGIECATHERINEP

…creen nav

2024-03-27 20:38 UTC, novadeveloper14 approved these changes
El desarrollo es correcto

2024-04-01 14:53 UTC, Sebas3245 approved these changes

2024-04-01 14:54 UTC, Sebas3245 requested changes
Solucionar conflictos

2024-04-01 16:25 UTC, Sebas3245 requested changes

2024-04-01 16:25 UTC, Sebas3245 commented on src/config/nav.tsx
> +          label: "Mis solicitudes",
Eliminaste la opcion pagos que es la que hay que dejar

2024-04-01 19:21 UTC, Sebas3245 approved these changes

2024-04-01 19:21 UTC, merged